### ISSUE TITLE
ByteScheduler: Tensorflow PS' graph-rewrite did not consider Identity Node

### ISSUE THREAD

**Issue by weidai0903** [bytedance/byteps#104]
In PSRewritePass, which inserts new ByteScheduler-specific nodes, when searching for variable ,send nodes, etc, it does not consider the fact that Tensorflow has inserted Identity nodes between Variable op and Send op, and thus the task map cannot be correctly formulated.  Any thought on this?

**Comment by byronyi** [comment]
That is correct and we welcome any contributions on this.
