### ISSUE TITLE
Does byteps support windows win10 for example?

### ISSUE THREAD

**Issue by handsomehu** [bytedance/byteps#120]
Hi guys,
Thank you for the good work. I notice that the installation need GCC, does it mean we could only use Linux to run byteps?
Does it support windows? do you guys have plan to support windows?
Thank you and have a nice day,
Leon

**Comment by bobzhuyb** [comment]
There are some Linux-specific parts in BytePS right now, so it is not trivial to make it compatible with Windows. We don't have a plan yet.

**Comment by handsomehu** [comment]
Thank you!
