### ISSUE TITLE
Better error message for missing env var

### ISSUE THREAD

**Issue by eric-haibin-lin** [bytedance/byteps#127]
**Describe the bug**
When some necessary env vars are missing, bytePS reports segmentation fault. 

**To Reproduce**
```

ubuntu@ip-172-31-47-42:~/cluster-sync$ nvidia-docker run -it -v ~/.ssh:/root/.ssh --network=host --shm-size=32768m bytepsimage/byteps_server:latest
root@ip-172-31-47-42:~#
root@ip-172-31-47-42:~#
root@ip-172-31-47-42:~# export DMLC_ROLE=server; python /usr/local/byteps/launcher/launch.py
BytePS launching server
Segmentation fault (core dumped)
```

**Expected behavior**
report a user-friendly error msg 

**Screenshots**

**Environment (please complete the following information):**
 - OS:
 - GCC version:
 - CUDA and NCCL version:
 - Framework (TF, PyTorch, MXNet):

**Additional context**

**Comment by ymjiang** [comment]
Thanks for your report. We will consider improving this and https://github.com/bytedance/byteps/issues/126 together.

**Comment by ymjiang** [comment]
Addressed by https://github.com/bytedance/byteps/pull/128
