### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by zmx19951103** [bytedance/byteps#154]
**Describe the bug**
I run the `python setup.py install` command to install byteps, when finished , i import the byteps.tensorflow.keras as bps, error occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/byteps/byteps/tensorflow/__init__.py", line 24, in <module>
    from byteps.tensorflow.ops import broadcast, _push_pull
  File "/root/byteps/byteps/tensorflow/ops.py", line 50, in <module>
    C_LIB = _load_library('c_lib' + get_ext_suffix())
  File "/root/byteps/byteps/tensorflow/ops.py", line 46, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/zmx/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /root/byteps/byteps/tensorflow/c_lib.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory

it seems that the .so file is not found and i check the .so file is under the build dir, so not found.

**Comment by bobzhuyb** [comment]
Your installation does not look right. The path should not be `/root/byteps/byteps/tensorflow/.....` This is your code path, not your python installation path. I suspect that you are still in the code folder when you try this, and python find the local byteps folder instead of the installed one. Would you go to other folders and try again?

**Comment by zmx19951103** [comment]
i change to other dir  and run cmd `import byteps.torch ` and `import byteps.tensorflow`, it successed. but cmd `import byteps.tensorflow.keras as bps` , no module named 'byteps.tensorflow.keras'

**Comment by bobzhuyb** [comment]
It should be `import byteps.keras as bps`. See https://github.com/bytedance/byteps/blob/master/example/keras/keras_imagenet_resnet50.py#L23

**Comment by zmx19951103** [comment]
ok, thanks.
