### ISSUE TITLE
How to compile byteps?

### ISSUE THREAD

**Issue by hbsun2113** [bytedance/byteps#160]
Hi, I want to change the source code(mostly is c++) of byteps and attempt to do some optimization. 
Now my re-compile step is 
```
pip uninstall -y byteps
python setup.py clean --all
python setup.py install
```
I think the speed of compilation and install is slow?  Can you tell me how to speed up? like, make -j4?

**Comment by bobzhuyb** [comment]
Compiling byteps itself should be quite fast. The time for compiling zmq and protobuf is much longer, but you only need to do it once. How long does it take for you to recompile byteps?

**Comment by xiongji** [comment]
> Hi, I want to change the source code(mostly is c++) of byteps and attempt to do some optimization.
> Now my re-compile step is
> 
> ```
> pip uninstall -y byteps
> python setup.py clean --all
> python setup.py install
> ```
> 
> I think the speed of compilation and install is slow? Can you tell me how to speed up? like, make -j4?



> Compiling byteps itself should be quite fast. The time for compiling zmq and protobuf is much longer, but you only need to do it once. How long does it take for you to recompile byteps?

I download the protobuf and zmq tgz file to local and remove the wget code line in deps.mk. Uncompress the local tgz directly. And it works well. 
May it be helpful to you.

**Comment by hbsun2113** [comment]
> > Hi, I want to change the source code(mostly is c++) of byteps and attempt to do some optimization.
> > Now my re-compile step is
> > ```
> > pip uninstall -y byteps
> > python setup.py clean --all
> > python setup.py install
> > ```
> > 
> > 
> > I think the speed of compilation and install is slow? Can you tell me how to speed up? like, make -j4?
> 
> > Compiling byteps itself should be quite fast. The time for compiling zmq and protobuf is much longer, but you only need to do it once. How long does it take for you to recompile byteps?
> 
> I download the protobuf and zmq tgz file to local and remove the wget code line in deps.mk. Uncompress the local tgz directly. And it works well.
> May it be helpful to you.

I got it! Thank you~
