### ISSUE TITLE
How to debug distributed mod?

### ISSUE THREAD

**Issue by hbsun2113** [bytedance/byteps#161]
I only have one worker and want to debug distributed mod. I export BYTEPS_FORCE_DISTRIBUTED=1 like this but failed. What others should I set?
![image](https://user-images.githubusercontent.com/27994442/69490957-aa80bb00-0ec9-11ea-8e22-4dae9fb2280e.png)
![image](https://user-images.githubusercontent.com/27994442/69490975-d13ef180-0ec9-11ea-9190-2db2e5830311.png)

**Comment by hbsun2113** [comment]
[2019-11-24 06:59:34.338323: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.0.conv2.weight, declared key (not PS key): 299 rank=2
[2019-11-24 06:59:34.338335: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.0.conv3.weight, declared key (not PS key): 300 rank=2
[2019-11-24 06:59:34.338347: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.0.downsample.0.weight, declared key (not PS key): 301 rank=2
[2019-11-24 06:59:34.338358: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.0.downsample.1.bias, declared key (not PS key): 302 rank=2
[2019-11-24 06:59:34.338370: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.0.downsample.1.weight, declared key (not PS key): 303 rank=2
[2019-11-24 06:59:34.338382: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.bn1.bias, declared key (not PS key): 304 rank=2
[2019-11-24 06:59:34.338394: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.bn1.weight, declared key (not PS key): 305 rank=2
[2019-11-24 06:59:34.338406: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.bn2.bias, declared key (not PS key): 306 rank=2
[2019-11-24 06:59:34.338417: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.bn2.weight, declared key (not PS key): 307 rank=2
[2019-11-24 06:59:34.338429: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.bn3.bias, declared key (not PS key): 308 rank=2
[2019-11-24 06:59:34.338440: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.bn3.weight, declared key (not PS key): 309 rank=2
[2019-11-24 06:59:34.338452: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.conv1.weight, declared key (not PS key): 310 rank=2
[2019-11-24 06:59:34.338464: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.conv2.weight, declared key (not PS key): 311 rank=2
[2019-11-24 06:59:34.338490: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.1.conv3.weight, declared key (not PS key): 312 rank=2
[2019-11-24 06:59:34.338503: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.bn1.bias, declared key (not PS key): 313 rank=2
[2019-11-24 06:59:34.338515: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.bn1.weight, declared key (not PS key): 314 rank=2
[2019-11-24 06:59:34.338527: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.bn2.bias, declared key (not PS key): 315 rank=2
[2019-11-24 06:59:34.338538: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.bn2.weight, declared key (not PS key): 316 rank=2
[2019-11-24 06:59:34.338550: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.bn3.bias, declared key (not PS key): 317 rank=2
[2019-11-24 06:59:34.338562: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.bn3.weight, declared key (not PS key): 318 rank=2
[2019-11-24 06:59:34.338573: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.conv1.weight, declared key (not PS key): 319 rank=2
[2019-11-24 06:59:34.338585: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.conv2.weight, declared key (not PS key): 320 rank=2
[2019-11-24 06:59:34.338597: D byteps/common/global.cc:320] Declared tensor byteps.Parameter.layer4.2.conv3.weight, declared key (not PS key): 321 rank=2
src/tcmalloc.cc:278] Attempt to free invalid pointer 0x7f31a96d9308
[2019-11-24 06:59:34.344418: D byteps/common/operations.cc:230] byteps.Parameter.bn1.bias partitioned to 1 part(s), total_len=256, key_range=[10551296, 10551296] rank=2
example/pytorch/start_pytorch_byteps.sh: line 20: 124364 Aborted                 (core dumped) python $path/benchmark_byteps.py $@

**Comment by hbsun2113** [comment]
[nohup.txt](https://github.com/bytedance/byteps/files/3883302/nohup.txt)

**Comment by hbsun2113** [comment]
![image](https://user-images.githubusercontent.com/27994442/69491138-d00ec400-0ecb-11ea-8ada-97eb7a0bbcae.png)

**Comment by bobzhuyb** [comment]
Does it run normally in non-distributed mode? Did you start scheduler and server? We need your *complete* starting commands so that we can really help you.

**Comment by hbsun2113** [comment]
> Does it run normally in non-distributed mode? Did you start scheduler and server? We need your _complete_ starting commands so that we can really help you.

It runs normally in non-distributed mode. I did not start scheduler and server. Can you give me a guide about running distributed mode with only one worker like [this](https://github.com/bytedance/byteps/blob/master/docs/running.md)?

**Comment by hbsun2113** [comment]
@bobzhuyb If I set the BYTEPS_FORCE_DISTRIBUTED  as following, should I also start scheduler and server?
![image](https://user-images.githubusercontent.com/27994442/69492620-f50d3200-0edf-11ea-86e1-3c95441345b8.png)

**Comment by bobzhuyb** [comment]
> @bobzhuyb If I set the BYTEPS_FORCE_DISTRIBUTED as following, should I also start scheduler and server?
> ![image](https://user-images.githubusercontent.com/27994442/69492620-f50d3200-0edf-11ea-86e1-3c95441345b8.png)

If you set BYTEPS_FORCE_DISTRIBUTED, you must start at least one server and one scheduler, just like you are starting distributed training job. You can start the server and scheduler on the same machine as worker, and set DMLC_PS_ROOT_URI to be your local IP or even 127.0.0.1

**Comment by hbsun2113** [comment]
@bobzhuyb  
Hi, I follow the steps to start scheduler:
```
docker pull bytepsimage/byteps_server
docker run -it --net=host bytepsimage/byteps_server bash
export DMLC_NUM_WORKER=1
export DMLC_ROLE=scheduler 
export DMLC_NUM_SERVER=1 
export DMLC_PS_ROOT_URI=127.0.0.1
export DMLC_PS_ROOT_PORT=3034  
```

but meet the following problem, could you help me?
![image](https://user-images.githubusercontent.com/27994442/69505395-b1104080-0f64-11ea-826e-9954ee822663.png)

**Comment by hbsun2113** [comment]
![image](https://user-images.githubusercontent.com/27994442/69506802-23841f00-0f6b-11ea-9f89-5f84903fac19.png)

**Comment by bobzhuyb** [comment]
Why did you overwrite the BYTEPS_SERVER_MXNET_PATH? I don't think you should overwrite it.

Anyways, we'll get rid of the MXNet part in the BytePS soon, so you won't have this kind of problem anymore. See the `server` branch. We will merge it in a week or two, and update the docker image.

**Comment by hbsun2113** [comment]
@bobzhuyb If I do not overwrite the BYTEPS_SERVER_MXNET_PATH:
![image](https://user-images.githubusercontent.com/27994442/69511658-060b8100-0f7c-11ea-9e20-051b027fa5e4.png)

**Comment by bobzhuyb** [comment]
> @bobzhuyb If I do not overwrite the BYTEPS_SERVER_MXNET_PATH, there will be a problem:
> ![image](https://user-images.githubusercontent.com/27994442/69511658-060b8100-0f7c-11ea-9e20-051b027fa5e4.png)
> Is there a method that I can start the scheduler now?

This is very strange. The environmental variable should be there. See
https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.server#L29
or
https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.mix.mxnet15#L119

**Comment by hbsun2113** [comment]
Now I can start scheduler successfully with ```export DMLC_PS_ROOT_URI=127.0.0.1```:
![image](https://user-images.githubusercontent.com/27994442/69516853-f301ac80-0f8d-11ea-96bc-fceb0e6c38d1.png)
But if I change it to ```export DMLC_PS_ROOT_URI=xx.xx.xx.xx``` where ```xx.xx.xx.xx``` means a public ip, it failed as following:
![image](https://user-images.githubusercontent.com/27994442/69516964-4673fa80-0f8e-11ea-8efe-28fae5355930.png)
I think it is a bug for [ps-lite](https://github.com/dmlc/ps-lite/pull/136), do you notice it?

**Comment by bobzhuyb** [comment]
Is `xx.xx.xx.xx` an IP that belongs to the machine and visible to the docker? Is the DMLC_PS_ROOT_PORT port available?... What value did you set for DMLC_PS_ROOT_PORT ?

**Comment by hbsun2113** [comment]
> Is `xx.xx.xx.xx` an IP that belongs to the machine and visible to the docker? Is the DMLC_PS_ROOT_PORT port available?... What value did you set for DMLC_PS_ROOT_PORT ?

xx.xx.xx.xx is a public IP that belongs to the machine and visible to the docker.
DMLC_PS_ROOT_PORT is 3034, and I think it is available. The following is how to test the port:
I ``` python3 -m http.server``` in the docker and can visit ```xx.xx.xx.xx:3034``` by my chrome:
![image](https://user-images.githubusercontent.com/27994442/69520770-72947900-0f98-11ea-8aad-4f25670c07ca.png)
what the docker shows:
![image](https://user-images.githubusercontent.com/27994442/69520802-7f18d180-0f98-11ea-9f6e-80647d6d7928.png)

**Comment by bobzhuyb** [comment]
Can you set `PS_VERBOSE=2` when you run the scheduler? This will output more logs.

**Comment by hbsun2113** [comment]
> Can you set `PS_VERBOSE=2` when you run the scheduler? This will output more logs.

![image](https://user-images.githubusercontent.com/27994442/69539343-3e807e80-0fbf-11ea-9645-857e5cad4526.png)

**Comment by hbsun2113** [comment]
> Can you set `PS_VERBOSE=2` when you run the scheduler? This will output more logs.

![image](https://user-images.githubusercontent.com/27994442/69539434-6d96f000-0fbf-11ea-9599-41da98b6ed2b.png)

**Comment by bobzhuyb** [comment]
> > Is `xx.xx.xx.xx` an IP that belongs to the machine and visible to the docker? Is the DMLC_PS_ROOT_PORT port available?... What value did you set for DMLC_PS_ROOT_PORT ?
> 
> xx.xx.xx.xx is a public IP that belongs to the machine and visible to the docker.
> DMLC_PS_ROOT_PORT is 3034, and I think it is available. The following is how to test the port:
> I ` python3 -m http.server` in the docker and can visit `xx.xx.xx.xx:3034` by my chrome:
> ![image](https://user-images.githubusercontent.com/27994442/69520770-72947900-0f98-11ea-8aad-4f25670c07ca.png)
> what the docker shows:
> ![image](https://user-images.githubusercontent.com/27994442/69520802-7f18d180-0f98-11ea-9f6e-80647d6d7928.png)
> 
> My env is:
> ![image](https://user-images.githubusercontent.com/27994442/69521134-42010f00-0f99-11ea-8349-bc905876e437.png)



> > Is `xx.xx.xx.xx` an IP that belongs to the machine and visible to the docker? Is the DMLC_PS_ROOT_PORT port available?... What value did you set for DMLC_PS_ROOT_PORT ?
> 
> xx.xx.xx.xx is a public IP that belongs to the machine and visible to the docker.
> DMLC_PS_ROOT_PORT is 3034, and I think it is available. The following is how to test the port:
> I ` python3 -m http.server` in the docker and can visit `xx.xx.xx.xx:3034` by my chrome:
> ![image](https://user-images.githubusercontent.com/27994442/69520770-72947900-0f98-11ea-8aad-4f25670c07ca.png)
> what the docker shows:
> ![image](https://user-images.githubusercontent.com/27994442/69520802-7f18d180-0f98-11ea-9f6e-80647d6d7928.png)
> 
> My env is:
> ![image](https://user-images.githubusercontent.com/27994442/69521134-42010f00-0f99-11ea-8349-bc905876e437.png)

Let's clarify a few things..

1. Can you bind your HTTP server to the `162.x.x.x` IP and 3034 port? 

2. When you say `162.x.x.x` "belongs to the machine", do you mean the public IP is assigned by OpenStack/K8S/other cloud, or do you mean that it actually shows up in `ifconfig`?

I feel that `162.x.x.x` is not an IP that can be bound locally.

**Comment by hbsun2113** [comment]
> Let's clarify a few things..
> 
> 1. Can you bind your HTTP server to the `162.x.x.x` IP and 3034 port?
> 2. When you say `162.x.x.x` "belongs to the machine", do you mean the public IP is assigned by OpenStack/K8S/other cloud, or do you mean that it actually shows up in `ifconfig`?
> 
> I feel that `162.x.x.x` is not an IP that can be bound locally.

You are right! When I change the IP to what ```ifconfig``` shows,  the scheduler can start successfully.
I want to know can I change the port of server or worker because my machine only has several available ports.

**Comment by bobzhuyb** [comment]
What do you mean by `available ports`? Are you referring to the ports allowed by the cloud's security group? The `172.x.x.x` IP is an internal IP within a subnet, which should not be affected by security groups... For now I don't think you can specify the worker port. It will bind to a random port. This is ps-lite's logic. 

From your screenshot, it does not look like IP binding/connection problem..

**Comment by hbsun2113** [comment]
> What do you mean by `available ports`? Are you referring to the ports allowed by the cloud's security group? The `172.x.x.x` IP is an internal IP within a subnet, which should not be affected by security groups... For now I don't think you can specify the worker port. It will bind to a random port. This is ps-lite's logic.
> 
> From your screenshot, it does not look like IP binding/connection problem..

Agree with you that it is not the port problem. So why did worker crash?

**Comment by hbsun2113** [comment]
@bobzhuyb 

![image](https://user-images.githubusercontent.com/27994442/69595529-c8216200-103a-11ea-931d-610541179fa2.png)

**Comment by bobzhuyb** [comment]
Are you using the docker image provided by us or built from code by yourself? Can you confirm that the same build work okay in non-distributed mode?

There is a knob here https://github.com/bytedance/byteps/blob/master/launcher/launch.py#L37 that allows you to run the program with gdb. Hopefully it will give us more info..

**Comment by hbsun2113** [comment]
> Are you using the docker image provided by us or built from code by yourself? Can you confirm that the same build work okay in non-distributed mode?
> 
> There is a knob here https://github.com/bytedance/byteps/blob/master/launcher/launch.py#L37 that allows you to run the program with gdb. Hopefully it will give us more info..

1.  I built from code by myself. 
2. The same build work okay in non-distributed mode:
![image](https://user-images.githubusercontent.com/27994442/69597999-ceb3d780-1042-11ea-88d2-536fe043f216.png)
and the env is:
![image](https://user-images.githubusercontent.com/27994442/69598012-db383000-1042-11ea-86e5-f9e896731811.png)
I also notice that:
![image](https://user-images.githubusercontent.com/27994442/69598037-f1de8700-1042-11ea-90d1-bdc78bc2752b.png)

3. but if I ```export BYTEPS_FORCE_DISTRIBUTED=1```:
![image](https://user-images.githubusercontent.com/27994442/69598103-34a05f00-1043-11ea-94f4-8191fc9da9c6.png)


4. GDB: Sorry I do not have the authority to restart docker container with gdb:
![image](https://user-images.githubusercontent.com/27994442/69598434-45050980-1044-11ea-8fb0-130f63cff0be.png)

**Comment by bobzhuyb** [comment]
It's just a warning. The problem is that byteps launcher uses gdb to start the shell script `example/pytorch/start_pytorch_byteps.sh`.. Can you avoid using `example/pytorch/start_pytorch_byteps.sh` and just use the launcher to start a python script in `hbsun_run.sh` ?
