### ISSUE TITLE
How does ```_enable_async``` works ?

### ISSUE THREAD

**Issue by hbsun2113** [bytedance/byteps#162]
I think BYTEPS_ENABLE_ASYNC==0 by default and then BYTEPS runs in the following step:
1. Computation: Each GPU performs computation (forward/backward propagation), which is irrelevant to BytePS;
2. Local Reduce: Multiple GPUs on the same machine reduces the gradients;
3. Push: The workers push the aggregated gradients to the servers;
4. Global Reduce: Once the servers receive the gradients from different workers, it aggregates the gradients;
5. Pull: The workers pull the aggregated gradients from the servers;
6. Local Broadcast: The workers broadcasts the updated gradients to local GPUs;
7. Goto next iteration and repeat from 1.

I want to know if I ```export BYTEPS_ENABLE_ASYNC=1```,  the above steps are changed? If so, what does an iteration go?

**Comment by bobzhuyb** [comment]
The main workflow on the worker side will be the same. The way server sums tensors will be different.

**Comment by hbsun2113** [comment]
> The main workflow on the worker side will be the same. The way server sums tensors will be different.
> 
> With `BYTEPS_ENABLE_ASYNC=0`, the server will wait for all workers' PUSH before perform PULL. However, `BYTEPS_ENABLE_ASYNC=1` means the server will perform PULL immediate after a worker's PUSH finishes.

For Step2 with ```BYTEPS_ENABLE_ASYNC=1```,  multiple GPUs on the same machine will wait for each other?  So this is not completely asynchronous？

**Comment by bobzhuyb** [comment]
> > The main workflow on the worker side will be the same. The way server sums tensors will be different.
> > With `BYTEPS_ENABLE_ASYNC=0`, the server will wait for all workers' PUSH before perform PULL. However, `BYTEPS_ENABLE_ASYNC=1` means the server will perform PULL immediate after a worker's PUSH finishes.
> 
> For Step2 with `BYTEPS_ENABLE_ASYNC=1`, multiple GPUs on the same machine will wait for each other? So this is not completely asynchronous？

Right. Within a single machine, it's synchronous because we assume that usually you have the same type of GPUs on a single machine. However, if you really want per-GPU asynchronous training, you can start X 1-GPU worker dockers on a X-GPU machine.. This will hurt your performance badly because each machine has to send X times traffic.

**Comment by hbsun2113** [comment]
I got it. Thank you.
