### ISSUE TITLE
How to enable gdb for byteps?

### ISSUE THREAD

**Issue by hbsun2113** [bytedance/byteps#164]
When I ```export BYTEPS_ENABLE_GDB=0```:
![image](https://user-images.githubusercontent.com/27994442/69607265-e188d500-105f-11ea-8fa3-1b1495512c5d.png)

When I ```export BYTEPS_ENABLE_GDB=1```:
![image](https://user-images.githubusercontent.com/27994442/69607316-febda380-105f-11ea-8054-8d64fb44425a.png)

**Comment by bobzhuyb** [comment]
See my comments. https://github.com/bytedance/byteps/issues/161#issuecomment-558489802

Can you try not to use `start_pytorch_byteps.sh` in your script, and directly use python instead? Otherwise, gdb only works on the shell script, not the actual python code.

**Comment by hbsun2113** [comment]
> See my comments. [#161 (comment)](https://github.com/bytedance/byteps/issues/161#issuecomment-558489802)
> 
> Can you try not to use `start_pytorch_byteps.sh` in your script, and directly use python instead? Otherwise, gdb only works on the shell script, not the actual python code.

My script is :
```
source hbsun_env_worker.sh
python launcher/launch.py example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 5
```
What should I change?

**Comment by hbsun2113** [comment]
I got it. Thank you.
