### ISSUE TITLE
core dump in running tensorflow benchmark

### ISSUE THREAD

**Issue by myotheone** [bytedance/byteps#18]
I have successfully installed byteps using "python setup.py install".
when i run benchmark, byteps core dumped.

core backtrack:
![image](https://user-images.githubusercontent.com/960748/60320708-1dcee100-99ad-11e9-972f-d9b40dd6c1f2.png)

env:
1.tf version 1.14
2.cuda version: 9.0
3.nccl version: 2.4.7 for cuda9.0
4.os: ubuntu 16.04
5.g++: 5.4.0

script: copy from step_by_step_tutorial.md
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64/:$LD_LIBRARY_PATH
export NVIDIA_VISIBLE_DEVICES=0,1,2,3
export DMLC_WORKER_ID=0
export DMLC_NUM_WORKER=1
export DMLC_ROLE=worker
export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=x.x.x.x
export DMLC_PS_ROOT_PORT=9999 
export EVAL_TYPE=benchmark

python /home/mark/mark/code/byteps/launcher/launch.py \                        
       /home/mark/mark/code/byteps/example/tensorflow/run_tensorflow_byteps.sh \                                                                          
       --model ResNet50 --num-iters 1000

**Comment by ymjiang** [comment]
Looks like your gcc version is higher than our tested gcc-4.9. 
Can you try to pin down gcc before you build BytePS? Here is an example: https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.pytorch#L122-L130

**Comment by bobzhuyb** [comment]
I think it's a very similar issue as this https://github.com/tensorflow/tensorflow/issues/13308#issuecomment-450202176
It happens when BytePS is compiled with gcc 5 while TF is compiled with gcc 4. 

It's still an open issue..

**Comment by un-knight** [comment]
I run the pytorch benchmark example, and meet the same core dump error.

```
/usr/local/byteps/example/pytorch/start_pytorch_byteps.sh: line 20:    30 Aborted                 (core dumped) python $path/benchmark_byteps.py $@
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/anaconda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/byteps/launcher/launch.py", line 19, in worker
    subprocess.check_call(command, env=my_env, stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/opt/anaconda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/byteps/example/pytorch/start_pytorch_byteps.sh --model resnet50 --num-iters 1000' returned non-zero exit status 134.
```

**Comment by ymjiang** [comment]
@un-knight Can you share more information about your OS and env?

**Comment by bobzhuyb** [comment]
@un-knight Would you reply to the issue thread you already opened? From your log, I don't see how your question is related to this issue.

**Comment by byronyi** [comment]
Just provide the binary release. No need to build one on users' environment, we do not need `mpicc` or `mpicxx`.

**Comment by bobzhuyb** [comment]
Our plan is to release binary installation package built for different frameworks/CUDA versions, in order to ease user installation process.

**Comment by ymjiang** [comment]
@myotheone We just uploaded some pypi lists for easier installation. See https://github.com/bytedance/byteps/blob/master/docs/pip-list.md

**Comment by bobzhuyb** [comment]
Closing this since we started providing pypi packages. Feel free to reopen.
