### ISSUE TITLE
Why pull gradients instead of model parameters?

### ISSUE THREAD

**Issue by hbsun2113** [bytedance/byteps#180]
Hey, I notice that BytesPs runs as following:
```
1. Computation: Each GPU performs computation (forward/backward propagation), which is irrelevant to BytePS;
2. Local Reduce: Multiple GPUs on the same machine reduces the gradients;
3. Push: The workers push the aggregated gradients to the servers;
4. Global Reduce: Once the servers receive the gradients from different workers, it aggregates the gradients;
5. Pull: The workers pull the aggregated gradients from the servers;
6. Local Broadcast: The workers broadcasts the updated gradients to local GPUs;
7. Goto next iteration and repeat from 1.
```
For a classical PS-architecture,  the worker pulls the model parameter instead of gradients. Why BytePs pulls the gradient(Step 5) instead of the model?

**Comment by zhongyuchen** [comment]
Workers will update the parameters locally. The only difference is that each worker maintains its own optimizer and do the SGD locally after pulling gradients while in your case the servers maintain a global optimizer and update the parameters.

**Comment by hbsun2113** [comment]
I got it, thanks!
