### ISSUE TITLE
Dockerfile cannot work.

### ISSUE THREAD

**Issue by ChrisQiqiang** [bytedance/byteps#183]
Using the docker image built by Dockerfile.Mxnet, cuda error happened as follows:
Stack trace:
  [bt] (0) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x2e6b160)                                                                                                                                                                                                [0x7ff0cd1bb160]
  [bt] (1) /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7ff128c02f20]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x3217a29)                                                                                                                                                                                                [0x7ff0cd567a29]
  [bt] (3) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32193bd)                                                                                                                                                                                                [0x7ff0cd5693bd]
  [bt] (4) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x3219afe)                                                                                                                                                                                                [0x7ff0cd569afe]
  [bt] (5) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x321a482)                                                                                                                                                                                                [0x7ff0cd56a482]
  [bt] (6) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x321bb73)                                                                                                                                                                                                [0x7ff0cd56bb73]
  [bt] (7) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x3222310)                                                                                                                                                                                                [0x7ff0cd572310]
  [bt] (8) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x25db7b9)                                                                                                                                                                                                [0x7ff0cc92b7b9]
[2019-12-19 15:00:48.336899: F byteps/common/core_loops.cc:299] Check failed: r                                                                                                                                                                                                == ncclSuccess NCCL error: unhandled cuda error
Aborted (core dumped)

How can I solve it? It still works well a few hours before.

**Comment by ymjiang** [comment]
@ChrisQiqiang Would you fallback to ba6b63b5f54b39d912463904629a90236b297f81 and try build the docker again? We just updated the nccl version from 2.4.2 to 2.4.8 in the dockerfile (https://github.com/bytedance/byteps/pull/182).
