### ISSUE TITLE
#pragma omp compile error

### ISSUE THREAD

**Issue by lambdaji** [bytedance/byteps#2]
byteps/common/cpu_reducer.cc:64:26: error: expected '#pragma omp' clause before 'simd'

**Comment by bobzhuyb** [comment]
Would you provide us more information about your environment? Are you building byteps using our dockerfile? If not, what is your gcc version?

This is related to the OpenMP version. We have tested gcc 4.9 and above, which includes OpenMP 4.0. I guess we'll need a flag to detect gcc version and choose omp clause accordingly.

**Comment by byronyi** [comment]
> byteps/common/cpu_reducer.cc:64:26: error: expected '#pragma omp' clause before 'simd'

Mind to share your environment, e.g. OS, compiler version, CUDA version etc.?

**Comment by lambdaji** [comment]
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

**Comment by byronyi** [comment]
Could you yum install devtoolset-7?

**Comment by lambdaji** [comment]
> Could you yum install devtoolset-7?

It works, thank you

**Comment by bobzhuyb** [comment]
Okay. Good to know. In general, we recommend starting with our dockerfiles, so that you will have less version issues. 

If not, you must have gcc>=4.9.

We may add a compilation flag to disable OpenMP in the future, since it is not always needed by BytePS.

**Comment by byronyi** [comment]
> > Could you yum install devtoolset-7?
> 
> It works, thank you

Good to know. I will close for now. Let us know if you have any other issues!
