### ISSUE TITLE
Question: Do I need compile with exactly gcc4.9 now?

### ISSUE THREAD

**Issue by zhongyuchen** [bytedance/byteps#214]
I notice a recent update in dockerfile. it seems that gcc4.9 is not a requirement now. Can I use the version as new as 9.2?

**Comment by bobzhuyb** [comment]
We have not tested 9.2... But we know 7.x should work now. If you find any problems with 9.2, please let us know.

**Comment by zhongyuchen** [comment]
I see. Thanks for you quick reply!
