### ISSUE TITLE
Could you tell me how multiple servers work and communicate in this framework?

### ISSUE THREAD

**Issue by wizard1203** [bytedance/byteps#221]
I need to use multiple servers for PS distributed training. And I am curious of how your codes run if there are multiple servers. 
In detail, I would appreciate that if you could tell me,
1. Does a single server store a whole model or a part of model?
2. How workers communicate with multiple servers?
3. How servers communicate with each other if needed?

**Comment by ymjiang** [comment]
> 1. Does a single server store a whole model or a part of model?

A part of the model.

> 2. How workers communicate with multiple servers?

At initialization, a worker partitions its gradient tensors and allocates them to multiple servers in load-balanced manner. After that, the worker constantly sends the each gradient tensors to the 
associated servers in each iteration.

> 3. How servers communicate with each other if needed?

The server processes only communicate with worker processes.

**Comment by gongjingcs** [comment]
hi, I just wonder in distributed mode, servers do not need communicate with each other for combing grads from all machines?

**Comment by bobzhuyb** [comment]
Servers do not need to communicate with other servers. They are maintaining different parts of the model, resprctively.

@gongjingcs Why do you think that is needed?

**Comment by wizard1203** [comment]
@ymjiang Thank you. Your answers help me a lot.  

@gongjingcs @bobzhuyb There are different communication schemes. Every server can receive several models from several workers rather than all workers, and they locally do reduce to get a model and communicate with each other to aggregate all local models.
