### ISSUE TITLE
Check failed: npending >= 0 (-1 vs. 0) 

### ISSUE THREAD

**Issue by gongjingcs** [bytedance/byteps#224]
[I want to ask for help!]
I use byteps in mxnet for vgg 16 training
I use 2 nodes,node 1 start a server and a worker, the second node starts a scheduler, a server and a worker.
as I know, it is a co-locate mode for byteps. But I get the following error:
F0319 10:24:13.783596  1076 threaded_engine.cc:480] Check failed: npending >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:13.826696  1279 threaded_engine.cc:480] Check failed: npending >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:13.826697  1280 threaded_engine.cc:480] Check failed: npending >= 0 (-2 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:13.927567  1282 threaded_engine.cc:480] Check failed: npending >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:14.105319  1283 threaded_engine.cc:480] Check failed: npending >= 0 (-2 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:14.105319  1284 threaded_engine.cc:480] Check failed: npending >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:14.247663  1286 threaded_engine.cc:480] Check failed: npending >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:14.247666  1285 threaded_engine.cc:480] Check failed: npending >= 0 (-2 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:14.320034  1287 threaded_engine.cc:480] Check failed: npending >= 0 (-2 vs. 0) 
*** Check failure stack trace: ***
F0319 10:24:14.320020  1288 threaded_engine.cc:480] Check failed: npending >= 0 (-1 vs. 0)

**Comment by bobzhuyb** [comment]
Would you tell us your detailed setup, like MXNet version, gcc version, how you set the environmental variables, etc.?

**Comment by gongjingcs** [comment]
My MXNet  is 1.5x
environmental variables：

scheduler：launch in node1
export PS_VERBOSE=2
export DMLC_NUM_WORKER=2
export DMLC_ROLE=scheduler 
export DMLC_NUM_SERVER=2
export DMLC_PS_ROOT_URI=182.168.42.146  # the scheduler IP 
export DMLC_PS_ROOT_PORT=1234  # the scheduler port
python3 /usr/local/byteps/launcher/launch.py

server：launch in node1 and node2
export DMLC_NUM_WORKER=2
export DMLC_ROLE=server
export DMLC_NUM_SERVER=2
export DMLC_PS_ROOT_URI=182.168.42.146     # the scheduler IP
export DMLC_PS_ROOT_PORT=1234  # the scheduler port
python3 /usr/local/byteps/launcher/launch.py

worker 01：launch in node1
export MXNET_CUDNN_AUTOTUNE_DEFAULT=0
export BYTEPS_PARTITION_BYTES=4096000
export NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export DMLC_WORKER_ID=0
export DMLC_NUM_WORKER=2
export DMLC_ROLE=worker 
export DMLC_NUM_SERVER=2
export DMLC_PS_ROOT_URI=182.168.42.146   # the scheduler IP 
export DMLC_PS_ROOT_PORT=1234 # the scheduler port

worker 02：launch in node2
export MXNET_CUDNN_AUTOTUNE_DEFAULT=0
export BYTEPS_PARTITION_BYTES=4096000
export NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export DMLC_WORKER_ID=1
export DMLC_NUM_WORKER=2
export DMLC_ROLE=worker 
export DMLC_NUM_SERVER=2
export DMLC_PS_ROOT_URI=182.168.42.146   # the scheduler IP 
export DMLC_PS_ROOT_PORT=1234 # the scheduler port

**Comment by gongjingcs** [comment]
> Would you tell us your detailed setup, like MXNet version, gcc version, how you set the environmental variables, etc.?

I use byteps/mxnet/ train_imagenet_byteps.py ， default is resnet50 and then I change network to vgg .  Howerver resnet50 worked, vgg16 shows the error above

**Comment by ymjiang** [comment]
Seems that it is not a problem inside BytePS. Does running on single machine work?

**Comment by gongjingcs** [comment]
if vgg16 is runing only with mxnet, it's ok, howerver using byteps, single machine also reports the error above

**Comment by ymjiang** [comment]
@gongjingcs Are you running with the docker `bytepsimage/mxnet`? If not, can you try to reproduce it in the docker?

**Comment by gongjingcs** [comment]
finally I found if I unset this env : export BYTEPS_PARTITION_BYTES=4096000, vgg16 training works well. Thanks alot for all your response

**Comment by ymjiang** [comment]
Glad that it worked. But this does not make sense to me. `BYTEPS_PARTITION_BYTES` is set to 4096000 by default, so I don't think setting / unsetting that would make any difference..

**Comment by gongjingcs** [comment]
thanks I unset export BYTEPS_PARTITION_BYTES=4096000 and  export MXNET_CUDNN_AUTOTUNE_DEFAULT=0 it works. Then I only  unset MXNET_CUDNN_AUTOTUNE_DEFAULT=0 it also works. So we can infer it's env MXNET_CUDNN_AUTOTUNE_DEFAULT=0 make difference .
