### ISSUE TITLE
Does BytePS use asynchronous communication?

### ISSUE THREAD

**Issue by wizard1203** [bytedance/byteps#226]
In this document, https://github.com/bytedance/byteps/blob/master/docs/rationale.md, I see you said that "Finally, there are many other benefits of using PS over allreduce. For example, it does not have the synchronization cost when you train on large-scale". So, does BytePS use asynchronous communication? 

I guess that communication efficiency of a synchronous PS is worse than allreduce? Because the communication data of server is $n \tims m$, in which n is the number of GPUs and m the model size.

**Comment by vycezhong** [comment]
I think the author here means PS architecture supports asynchronous SGD while all-reduce does not. Actually BytePS supports both async & sync training. You can enable async training by specifying 'export BYTEPS_ENABLE_ASYNC=1' for  servers.

**Comment by bobzhuyb** [comment]
@wizard1203 

> communication efficiency of a synchronous PS is worse than allreduce

No. The whole point of rationale.md is to tell you that synchronous PS can be more efficient than all-reduce. 

> The communication data of server is $n \tims m$

True. However, if you have $n$ parameter servers, the data per server is amortized to just $m$. For all-reduce, each node must send and receive $2n/(n-1) \times m$ data.

**Comment by bobzhuyb** [comment]
BytePS supports both synchronous and asynchronous modes.

**Comment by acmore** [comment]
> BytePS supports both synchronous and asynchronous modes.

Thanks for open source this nice work!

Regarding the sync & async training, we tested asynchronous training using tensorflow example in the repo. We found that the async training is slower than the sync training on VGG16 and ResNet50. Is this reasonable?

**Comment by wizard1203** [comment]
@bobzhuyb 
For PS, don't we need to add the communication data of both push and pull together? So even there are $n$ parameter servers, the communication data is $2m$ ?

**Comment by bobzhuyb** [comment]
> @bobzhuyb
> For PS, don't we need to add the communication data of both push and pull together? So even there are $n$ parameter servers, the communication data is $2m$ ?

Push and pull can be overlapped with tensor partition + a good pipeline because the network is fully duplex. 

For all-reduce, every node has to send *and* receive $2(n-1)/n \times m$ data. It also overlaps sending and receiving. It's a fair comparison.

**Comment by bobzhuyb** [comment]
> > BytePS supports both synchronous and asynchronous modes.
> 
> Thanks for open source this nice work!
> 
> Regarding the sync & async training, we tested asynchronous training using tensorflow example in the repo. We found that the async training is slower than the sync training on VGG16 and ResNet50. Is this reasonable?

What do you mean by "training is slower"? If you are talking about model convergence speed, it's expected. If you are talking about system throughput, it's unexpected and we should investigate it.

**Comment by acmore** [comment]
> > > BytePS supports both synchronous and asynchronous modes.
> > 
> > 
> > Thanks for open source this nice work!
> > Regarding the sync & async training, we tested asynchronous training using tensorflow example in the repo. We found that the async training is slower than the sync training on VGG16 and ResNet50. Is this reasonable?
> 
> What do you mean by "training is slower"? If you are talking about model convergence speed, it's expected. If you are talking about system throughput, it's unexpected and we should investigate it.

I mean the system throughput is around 10% slower. My configuration is 1 server 2 workers, and the server is colocated with one worker, the other worker is at another machine.

If it's unexpected, I wonder if there is any documentation about the throughput of async training?

**Comment by ymjiang** [comment]
@acmore Async training involves extra copy, that is the additional cost compared to the synchronous baseline. If the two workers have very different training speed, you should see significant throughput improvement for the fast worker. Otherwise, you may not see improvement in this tradeoff.

**Comment by wizard1203** [comment]
> > @bobzhuyb
> > For PS, don't we need to add the communication data of both push and pull together? So even there are $n$ parameter servers, the communication data is $2m$ ?
> 
> Push and pull can be overlapped with tensor partition + a good pipeline because the network is fully duplex.
> 
> For all-reduce, every node has to send _and_ receive $2(n-1)/n \times m$ data. It also overlaps sending and receiving. It's a fair comparison.

Thank you for your explanation. I wonder if allreduce can make use of the same ideas of BytePSscheduler, i.e., tensor partition and crossing barrier.

And, do the Local Reduce and Local Broadcast increase the communication time? Or because these two operations are performed on a same machine, the operating time of this part is very little? If yes, I guess that more workers on a same machine, more efficient the communication is. And making the number of servers equal to worker machines is optimal.

**Comment by bobzhuyb** [comment]
> Thank you for your explanation. I wonder if allreduce can make use of the same ideas of BytePSscheduler, i.e., tensor partition and crossing barrier.
> 

Yes. 

> And, do the Local Reduce and Local Broadcast increase the communication time? Or because these two operations are performed on a same machine, the operating time of this part is very little? If yes, I guess that more workers on a same machine, more efficient the communication is. And making the number of servers equal to worker machines is optimal.

The local communication adds additional stages in the whole compute-push-pull-compute pipeline. The throughput of a pipeline is determined by the slowest stage. Since the local communication is usually faster than the network communication, it is unlikely to be the slowest stage. Thus, a well-implemented pipeline would not run slower with the local communication.

**Comment by acmore** [comment]
> @acmore Async training involves extra copy, that is the additional cost compared to the synchronous baseline. If the two workers have very different training speed, you should see significant throughput improvement for the fast worker. Otherwise, you may not see improvement in this tradeoff.

Thanks for explanation. Other than the extra copy, I guess the async training mode is like async training between workers compared to async training in other common PS architecture. The local rank has to wait for all the ranks in the same worker to allreduce and then update from parameter server. Am I right?

**Comment by ymjiang** [comment]
> The local rank has to wait for all the ranks in the same worker to allreduce and then update from parameter server. Am I right?

No, all ranks in the same worker are synchronous, because they are usually homogeneous. In our design, we allow different workers to have different training throughput (if you overlook the topology inside a worker).

**Comment by wizard1203** [comment]
> > Thank you for your explanation. I wonder if allreduce can make use of the same ideas of BytePSscheduler, i.e., tensor partition and crossing barrier.
> 
> Yes.
> 
> > And, do the Local Reduce and Local Broadcast increase the communication time? Or because these two operations are performed on a same machine, the operating time of this part is very little? If yes, I guess that more workers on a same machine, more efficient the communication is. And making the number of servers equal to worker machines is optimal.
> 
> The local communication adds additional stages in the whole compute-push-pull-compute pipeline. The throughput of a pipeline is determined by the slowest stage. Since the local communication is usually faster than the network communication, it is unlikely to be the slowest stage. Thus, a well-implemented pipeline would not run slower with the local communication.

Thank you. Now I understand it much more.

**Comment by bobzhuyb** [comment]
I believe that we have answered the questions. Closing this.
