### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by gongjingcs** [bytedance/byteps#229]
As I know， byteps‘s mode is ’per process per gpu‘ , so a worker normally has multi processes running in muti gpus with a worker. I wonder a worker need gather all grads from ranks with node and then push to server? It also need broadcast to ranks after pulling grads from servers?

**Comment by ymjiang** [comment]
Yes, your description is true. Did you encounter any specific problem?

**Comment by gongjingcs** [comment]
I researched various acceleration frameworks including horovod and byteps and others, but I found that the performance of byteps is better than horovod in my benchmark test. Horovod performance is not very good in tcp / rdma environment, so I would like to ask For your benchmark test of horovod, I can provide some of my test data and test environment

**Comment by ymjiang** [comment]
It is expected that BytePS outperforms Horovod with TCP/RDMA. Are you asking about how to optimize the performance for Horovod?

**Comment by gongjingcs** [comment]
On the one hand, I would like to ask whether the current test results of horovod are as expected, on the other hand, I also want to ask how to optimize the performance for Horovod

**Comment by gongjingcs** [comment]
Because  the performance of horovod and ps-lite I measured are similar, mainly for resnet101 and vgg16, the machine scale is 1 machine 8 gpus to 4 machines 32 gpus

**Comment by ymjiang** [comment]
I suggest you raise an issue for Horovod if you want to tune its performance. It is out of our scope.

> Because the performance of horovod and ps-lite I measured are similar

I am confused about this. Are you saying that the network throughput of Horovod and ps-lite are similar? If yes, then It makes sense that BytePS has better performance. You can refer to here: https://github.com/bytedance/byteps/blob/master/docs/rationale.md.

**Comment by gongjingcs** [comment]
Training speed  using horovod is similar to mxnet ps-lite

**Comment by bobzhuyb** [comment]
@gongjingcs So you are talking about three things, Horovod, BytePS, and MXNet native ps-lite. You find that BytePS performance is better than the other two, and Horovod and MXNet native ps-lite have similar performance. Do I understand you correctly?

For questions about how to optimize horovod performance, you should ask the Horovod community. To us, it's totally expected that BytePS performs better.

**Comment by gongjingcs** [comment]
Yes，BytePS performance is better than Horovod and MXNet native ps-lite.  Horovod and MXNet native ps-lite have similar performance.
