### ISSUE TITLE
install error:error: An ERROR occured while running the Makefile for the ps-lite library. Exit code: 2

### ISSUE THREAD

**Issue by yuxwhkbu** [bytedance/byteps#231]
**Describe the bug**

**To Reproduce**
1. git clone --recursive https://github.com/bytedance/byteps
cd byteps
python3 setup.py install
2.See error in make.log

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS:redhat
 - GCC version: 5.4.0/4.9/7.3.0 etc...
 - CUDA and NCCL version:cuda/10.0.130 nccl-v2.3.7
 - Framework (TF, PyTorch, MXNet): /

**Additional context**
Please find the details in the make.log. I don't think I used the wrong gcc - whichever version of gcc I tried, the compile will not be successful. Note that the following /GCC-4.8.5_GMP-6.1.1 route does not mean the GCC version is 4.8.5 in this example. (The last line shows the gcc version is 5.4.0)

[w@hsw226 byteps]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/cm/extra/apps/GCC/5.4.0/GCC-4.8.5_GMP-6.1.1_MPFR-3.1.5_MPC-1.0.
3/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --enable-shared --enable-threads --with-gmp=/cm/extra/a
pps/GMP/6.1.1/GCC-4.8.5 --with-mpfr=/cm/extra/apps/MPFR/3.1.5/GCC-4.8.5_GMP-6.1.1 --
with-mpfr-lib=/cm/extra/apps/MPFR/3.1.5/GCC-4.8.5_GMP-6.1.1/lib --with-mpc=/cm/extra
/apps/MPC/1.0.3/GCC-4.8.5_GMP-6.1.1_MPFR-3.1.5 --prefix=/cm/extra/apps/GCC/5.4.0/GCC
-4.8.5_GMP-6.1.1_MPFR-3.1.5_MPC-1.0.3
Thread model: posix
gcc version 5.4.0 (GCC)

**Could you please help me? Thank you!!**
[make.log](https://github.com/bytedance/byteps/files/4397864/make.log)

**Comment by ymjiang** [comment]
Does this work for you? 
`apt install build-essential libc6-dev`

**Comment by yuxwhkbu** [comment]
It is fixed now, thankyou!!
