### ISSUE TITLE
The benchmark hang

### ISSUE THREAD

**Issue by yuxwhkbu** [bytedance/byteps#233]
**Describe the bug**

**To Reproduce**
I successfully followed the step-by-step tutorial to benchmark on a single worker. When I go on for a distributed training, the servers hang. ( I can't use nvidia docker on this machine)  The command I use is listed as follows. Note that whether I set the server and scheduler on the same machine, the training hang. The ssh between all the machines is fine. Could you please help me? Thank you!

export NVIDIA_VISIBLE_DEVICES=0,1,2,3  
export DMLC_WORKER_ID=0 
export DMLC_NUM_WORKER=2 
export DMLC_ROLE=worker 
export DMLC_NUM_SERVER=1 
export DMLC_PS_ROOT_URI=10.1.82.20 # the scheduler IP 
export DMLC_PS_ROOT_PORT=9000 # the scheduler port
bpslaunch python3 /home/esetstore/yxwang/byteps/example/pytorch/benchmark_byteps.py --model resnet50 --num-iters 100

export NVIDIA_VISIBLE_DEVICES=0,1,2,3  
export DMLC_WORKER_ID=1
export DMLC_NUM_WORKER=2 
export DMLC_ROLE=worker 
export DMLC_NUM_SERVER=1 
export DMLC_PS_ROOT_URI=10.1.82.20 # the scheduler IP 
export DMLC_PS_ROOT_PORT=9000 # the scheduler port
bpslaunch python3 /home/esetstore/yxwang/byteps/example/pytorch/benchmark_byteps.py --model resnet50 --num-iters 100

export DMLC_NUM_WORKER=2 
export DMLC_ROLE=scheduler 
export DMLC_NUM_SERVER=1 
export DMLC_PS_ROOT_URI=10.1.82.20 # the scheduler IP 
export DMLC_PS_ROOT_PORT=9000  # the scheduler port
bpslaunch

export DMLC_NUM_WORKER=2 
export DMLC_ROLE=server  
export DMLC_NUM_SERVER=1 
export DMLC_PS_ROOT_URI=10.1.82.20 # the scheduler IP 
export DMLC_PS_ROOT_PORT=9000  # the scheduler port
bpslaunch

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45350678/78179439-c9a0e200-7493-11ea-98e1-f19feab9a03c.png)

**Environment (please complete the following information):**
 - OS: ubuntu
 - GCC version: /
 - CUDA and NCCL version:
export CUDA_HOME=/usr/local/cuda-10.1
export NCCL_HOME=/home/esetstore/downloads/nccl_2.4.7-1+cuda10.1_x86_64
export BYTEPS_NCCL_HOME=/home/esetstore/downloads/nccl_2.4.7-1+cuda10.1_x86_64
 - Framework (TF, PyTorch, MXNet): Pytorch

**Additional context**

**Comment by bobzhuyb** [comment]
After you start the scheduler, can you run the following command and tell us the output?
`netstat -ant|grep 9000`
`telnet 10.1.82.20 9000`

**Comment by yuxwhkbu** [comment]
![image](https://user-images.githubusercontent.com/45350678/78221534-203f0800-74f6-11ea-9e79-301c0cec41ae.png)
Sir, the outcome looks like this

**Comment by yuxwhkbu** [comment]
> After you start the scheduler, can you run the following command and tell us the output?
> `netstat -ant|grep 9000` -- this should be run on the same machine as your scheduler
> `telnet 10.1.82.20 9000` -- this should be run on the worker machine
> 
> BTW, I am closing the other issue you open earlier.


![](https://user-images.githubusercontent.com/45350678/78221534-203f0800-74f6-11ea-9e79-301c0cec41ae.png)
Sir, the outcome looks like this

**Comment by bobzhuyb** [comment]
Thank you. Your network looks fine. Would you set `PS_VERBOSE=2`, run again and tell us the log?

BTW, are you using the latest docker image, or using pip install, or compiling from source to install byteps?

**Comment by yuxwhkbu** [comment]
Thank you, it was the ip problem and it is fixed.

**Comment by bobzhuyb** [comment]
@yuxwhkbu Thank you for reporting.
