### ISSUE TITLE
LARS support in bytePS

### ISSUE THREAD

**Issue by wuchangping** [bytedance/byteps#246]
LARS is a very useful feature, could bytePS support it?

**Comment by vycezhong** [comment]
byteps serves as a communication framework to exchange gradients, independent of any optimization algorithm. How to optimize the network is the responsibility of the deep learning framework you use, not byteps's. Of course, you can implement LARS in MXNet/TF/PyTorch, and use byteps to aggregate gradients.

**Comment by ymjiang** [comment]
As @vycezhong said, LARS is not a communication feature, and should be implemented by the computation frameworks instead.
