### ISSUE TITLE
Adding more servers causes push and pull time increasing.

### ISSUE THREAD

**Issue by wizard1203** [bytedance/byteps#258]
Adding more servers causes push and pull time increasing, I am confused why this happens.
Theoretically, more servers make communication fast, but the experiment results show it does not.
Is there some reason?

**Comment by bobzhuyb** [comment]
Can you tell us your detailed setup? 

What you describe is certainly possible, e.g., adding a slow server (slower than other servers in terms of CPU or bandwidth) may slow down everything because of the nature of synchronized data parallel training.

**Comment by wizard1203** [comment]
> Can you tell us your detailed setup?
> 
> What you describe is certainly possible, e.g., adding a slow server (slower than other servers in terms of CPU or bandwidth) may slow down everything because of the nature of synchronized data parallel training.

Every machine has same performance.

Might the reason be that:
all workers push and pull the first part of the model to and from the first server at the same time, then the second part to and from the second server...... This would make the bandwidth utilization of many servers similar with it of only one server.

**Comment by bobzhuyb** [comment]
@wizard1203 No, all the network transmissions are asynchronous, meaning that a worker can push to the second server before the push to the first server finishes.

If you don't tell us more details about your configuration, we can't help you..

**Comment by bobzhuyb** [comment]
We have run it with 128 worker + 128 server and it worked just fine.

**Comment by wizard1203** [comment]
> @wizard1203 No, all the network transmissions are asynchronous, meaning that a worker can push to the second server before the push to the first server finishes.
> 
> If you don't tell us more details about your configuration, we can't help you..

I run experiments with 1-4 workers and 1-4 servers, using 10Gb/s TCP network and 100 Gb/s RDMA network. and every worker and server has 4 GPUs, CPU and other configurations of workers are same with servers.

**Comment by wizard1203** [comment]
> @wizard1203 No, all the network transmissions are asynchronous, meaning that a worker can push to the second server before the push to the first server finishes.
> 
> If you don't tell us more details about your configuration, we can't help you..

I run experiments on 1-4 workers and 1-4 servers, with 10Gp/s TCP network and 100Gp/s RDMA network. Only workers train the model, servers do not.

And each worker or server have 4 GPUs, the CPU and other configuration of them are the same.

And, I changed the code of torch/__init__.py, instead of asynchronously doing push_and_pull and backward of every tensor, I make it do push_and_pull after the backward of all tensors is finished, and push_and_pull a huge tensor including all tensors, and I increase the BYTEPS_PARTITION_BYTES to make it transmit the whole tensor in one communication rather than every part of it. Will this make the number of servers not influence the performance too much? My experiment results show the number of servers almost do not has a obvious relation with the push time and pull time.

**Comment by bobzhuyb** [comment]
If you want to leverage four servers, you should let BytePS have at least four partitions of tensors so that it can load balance the partitions onto different servers. I am not sure why you want to increase the partition size in the first place.

**Comment by wizard1203** [comment]
> If you want to leverage four servers, you should let BytePS have at least four partitions of tensors so that it can load balance the partitions onto different servers. I am not sure why you want to increase the partition size in the first place.

OHHHH,  I thought it will do more partition on the partitioned tensor to make load balance...... So I can make the BYTEPS_PARTITION_BYTES just equal to 1/4 of model size to make it balanced. Because I want to measure how the transmitting speed of push and pull influenced by the number of servers. Thank you, you are so kind~~
