### ISSUE TITLE
[question] When to Use BYTEPS_REDUCE_ROOTS

### ISSUE THREAD

**Issue by gaocegege** [bytedance/byteps#266]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hi, I found that BYTEPS_REDUCE_ROOTS is an environment variable. when it is set, we will use reduce and bcast instead reducescatter and allgather. I am wondering if we have such use scenario in production?

**Describe alternatives you've considered**

**Additional context**

**Comment by bobzhuyb** [comment]
Yes, in some cases `BYTEPS_REDUCE_ROOTS` can give you better performance. It depends on your internal PCIe topology. If you paste the output of `nvidia-smi topo -m`, I may be able to tell you whether you should set it.

**Comment by gaocegege** [comment]
Thanks for your reply.

> It depends on your internal PCIe topology.

Can you please explain more about it or do we have doc for the feature? I am just looking through the code base of BytePS and see if we can integrate it better on Kubernetes.

**Comment by bobzhuyb** [comment]
There is a paper pending publication. It has more detailed explanation.

A quick rule is -- 
IF your NIC is not sharing a PCIe switch with any of the GPUs, you should not set `BYTEPS_REDUCE_ROOTS` and keep using `reducescatter` and `allgather`.

However, IF your NIC is sharing a PCIe switch with some GPUs, you should set `BYTEPS_REDUCE_ROOTS` to be GPUs that are on **_other_** PCIe switches so that you can avoid PCIe contention between NIC and GPUs.

**Comment by gaocegege** [comment]
Thanks.

**Comment by Ruinhuang** [comment]
Hi, @bobzhuyb My topology is shown below. So how can i set up the value 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    mlx5_0  mlx5_1  mlx5_2  mlx5_3  CPU Affinity    NUMA Affinity
GPU0     X      NV1     NV2     NV1     NV2     SYS     SYS     SYS     PIX     NODE    SYS     SYS     0-23,48-71      0
GPU1    NV1      X      NV1     NV2     SYS     NV2     SYS     SYS     PIX     NODE    SYS     SYS     0-23,48-71      0
GPU2    NV2     NV1      X      NV2     SYS     SYS     NV1     SYS     NODE    PIX     SYS     SYS     0-23,48-71      0
GPU3    NV1     NV2     NV2      X      SYS     SYS     SYS     NV1     NODE    PIX     SYS     SYS     0-23,48-71      0
GPU4    NV2     SYS     SYS     SYS      X      NV1     NV2     NV1     SYS     SYS     PIX     NODE    24-47,72-95     1
GPU5    SYS     NV2     SYS     SYS     NV1      X      NV1     NV2     SYS     SYS     PIX     NODE    24-47,72-95     1
GPU6    SYS     SYS     NV1     SYS     NV2     NV1      X      NV2     SYS     SYS     NODE    PIX     24-47,72-95     1
GPU7    SYS     SYS     SYS     NV1     NV1     NV2     NV2      X      SYS     SYS     NODE    PIX     24-47,72-95     1
mlx5_0  PIX     PIX     NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    SYS     SYS
mlx5_1  NODE    NODE    PIX     PIX     SYS     SYS     SYS     SYS     NODE     X      SYS     SYS
mlx5_2  SYS     SYS     SYS     SYS     PIX     PIX     NODE    NODE    SYS     SYS      X      NODE
mlx5_3  SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS     SYS     NODE     X
