### ISSUE TITLE
potential race condition in server

### ISSUE THREAD

**Issue by vycezhong** [bytedance/byteps#273]
I suspect that SUM_RECV may suffer from race condition. There may be more than one threads writing to the same `updates.merged.tensor` simultaneously.  

https://github.com/bytedance/byteps/blob/cf020c97fc718ca209cbadbfac4cffa5e49d7d21/byteps/server/server.cc#L130-L152

https://github.com/bytedance/byteps/blob/cf020c97fc718ca209cbadbfac4cffa5e49d7d21/byteps/server/server.cc#L254

**Comment by bobzhuyb** [comment]
I don't get your point.. For a specific key, there is only one thread dealing with it, right?  cc @ymjiang

**Comment by vycezhong** [comment]
Oh you are right. `GetThreadID` will return the same tid for the same key. Thanks for your explanation.
