### ISSUE TITLE
RDMA compile error

### ISSUE THREAD

**Issue by wangshuaizs** [bytedance/byteps#28]
Hi,
I tried to enable RDMA for byteps, but the logs output that ```byteps/3rdparty/ps-lite/src/./rdma_van.h:663: undefined reference to `ibv_reg_mr'``` and some other ibv_* functions are similar. Compare to the install process without RDMA, I just add ```BYTEPS_USE_RDMA=1``` before installation. It seems that I need to specify the locations of my ```libibverbs.a```. If so, would you mind adding support for customizing libiverbs's location?

**Comment by changlan** [comment]
Please make sure you have installed librdmacm and libibverbs. If they are indeed installed, perhaps try adding their location to `LD_LIBRARY_PATH` beforehand.

**Comment by wangshuaizs** [comment]
@changlan , yes, it worked for worker node. But for server node and scheduler node, which have to use MXNet, the logs output
```
mxnet.base.MXNetError: [13:09:50] src/van.cc:80: unsupported van type: rdma
```
I am not familiar with MXNet. How can I enable rdma support for MXNet to run server and scheduler normally? Setting ```BYTEPS_USE_RDMA=1``` only works for worker node.

**Comment by changlan** [comment]
The MXNet in our Docker image does not enable RDMA. To enable, you need to manually rebuild MXNet on the server and scheduler node as following (adapted from https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.server#L72):
```
git clone --single-branch --branch byteps --recurse-submodules https://github.com/bytedance/incubator-mxnet
cd $BYTEPS_SERVER_MXNET_PATH && \
    make clean_all && make -j16 $SERVER_BUILD_OPTS
cd $BYTEPS_SERVER_MXNET_PATH && \
    cd python && \
    python setup.py build && \
    python setup.py install
```

**Comment by wangshuaizs** [comment]
@changlan , actually, I didn't use docker, just running in my physical machine. And I built MXNet following the guide in ```https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.server```, but the error still happened.

By the way, If I installed using ```python setup.py install```, how can I reinstall it?  I guess that script ```setup.py``` doesn't support reinstall.

**Comment by changlan** [comment]
Oh I see, you need to add `USE_RDMA=1` to the `SERVER_BUILD_OPTS` variable, which enables RDMA during MXNet compilation. We will add the more clarification to the document.

For now users need to manually remove BytePS files in Python's `site-packages` folder before reinstall. We are planning to release `whl`s so that we can `pip install/uninstall`.

**Comment by bobzhuyb** [comment]
You should be able to do the following
```
pip uninstall -y byteps
python setup.py clean --all
```

**Comment by changlan** [comment]
Would be good to include RDMA support in prebuilt docker, and then users can specify whether to enable RDMA at runtime. @ymjiang any thoughts?

**Comment by ymjiang** [comment]
Will take a look at this. Perhaps we should provide an image for RDMA.

@wangshuaizs For now please build server/scheduler images following @changlan 's instructions.

**Comment by XinYao1994** [comment]
In my case, I solve it by moving the "$(LIBS)" to the end of the line.
E.g.,
```
build/%.o: src/%.cc ${ZMQ} src/meta.pb.h
	@mkdir -p $(@D)
	- $(CXX) $(CFLAGS) $(LIBS) -c $< -o $@
	+ $(CXX) $(CFLAGS) -c $< -o $@ $(LIBS)
```
Also do the same thing to the test/test.mk, then it should work.
My test environment is QLogic + Ubuntu18.04

**Comment by bobzhuyb** [comment]
@changlan Have a look at the above?

**Comment by changlan** [comment]
Hi @wangshuaizs , any success in working with RDMA?

**Comment by changlan** [comment]
Thanks for @XinYao1994's tip. #42 has been merged.

@wangshuaizs: Closing this issue. Feel free to reopen it if you run into any problems.

**Comment by ymjiang** [comment]
@wangshuaizs Just released our RDMA images. May follow the tutorials here to reproduce:
https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md#distributed-training-with-rdma

**Comment by wangshuaizs** [comment]
@ymjiang  Thank you. I will try it. 

In the tutorial, it is said that `To run this example, your nvidia-docker need to support cuda 10'. I think that is for worker, rather than server and scheduler, right?

Another question is how can I specify `service level` if I run byteps based on RoCEv1?

**Comment by ymjiang** [comment]
@wangshuaizs Yes, only the workers need nvidia-docker. 

We only tested it on RoCEv2. I am not sure about what will happen on RoCEv1. @changlan @bobzhuyb @byronyi Any idea about this?
