### ISSUE TITLE
some question about setup.py

### ISSUE THREAD

**Issue by DeruiLiu** [bytedance/byteps#281]
Hi， when I use python setup.py install, it make an error:
wget https://raw.githubusercontent.com/mli/deps/master/build/zeromq-4.1.4.tar.gz && tar --no-same-owner -zxf zeromq-4.1.4.tar.gz
--2020-08-03 20:23:10--  https://raw.githubusercontent.com/mli/deps/master/build/zeromq-4.1.4.tar.gz
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by ***
Unable to locally verify the issuer's authority.
I know I need to add "--no-check-certificate"， but I don't know where can I add it to in setup.py? Can anyone help me?
maybe i need to find where the wget zeromq in the code, but I can not find it.

**Comment by vycezhong** [comment]
I think you should add it here. https://github.com/bytedance/ps-lite/blob/2f40b17737/make/deps.mk

**Comment by DeruiLiu** [comment]
> I think you should add it here. https://github.com/bytedance/ps-lite/blob/2f40b17737/make/deps.mk

yeah！I fixed it， thank you。
