### ISSUE TITLE
numa.h not found when building for pytorch

### ISSUE THREAD

**Issue by flint-stone** [bytedance/byteps#307]
**Describe the bug**
The building process fails because it cannot find numa.h. I have pytorch 1.6.0 installed. I also have libnuma installed.

**To Reproduce**
I followed the same steps from the README. Running with "python setup.py install"

**Screenshots**
See the error message below:

![image](https://user-images.githubusercontent.com/1960399/96932649-d19e8e80-1484-11eb-9dfc-126e1328122f.png)

**Environment (please complete the following information):**
 - OS: CentOS Linux release 7.6.1810
 - GCC version: gcc (GCC) 5.3.0
 - CUDA and NCCL version: CUDA 10.1,  NCCL 1.3.4 0
 - Framework (TF, PyTorch, MXNet): PyTorch 1.6.0

**Additional context**
My numactl lib is installed in a custom path (since I don't have root access to the server) and I install numa lib through conda. But I also found numa.h in my pytorch build (although it is under build/c10 which is not included during the build). Could this be the reason that the build has failed? Thanks!

**Comment by ymjiang** [comment]
> My numactl lib is installed in a custom path

Does exporting this custom path to the PATH env var works for you?

**Comment by bobzhuyb** [comment]
The header files should be in numactl-devel (in CentOS). Just numactl is not sufficient.

**Comment by flint-stone** [comment]
Thanks for the reply. I apologize for the confusion @bobzhuyb  -- I do have numactl-devel installed through [https://anaconda.org/conda-forge/numactl-devel-cos6-x86_64](conda). What I did was only to add the custom path to $PATH environment as @ymjiang  suggested. However I'm still getting the same error -- I wonder which location should be the path that compiler is reading from.

**Comment by bobzhuyb** [comment]
> Thanks for the reply. I apologize for the confusion @bobzhuyb -- I do have numactl-devel installed through [https://anaconda.org/conda-forge/numactl-devel-cos6-x86_64](conda). What I did was only to add the custom path to $PATH environment as @ymjiang suggested. However I'm still getting the same error -- I wonder which location should be the path that compiler is reading from.

If you don't mind editing the code a little bit, you can add the header folders here:
https://github.com/bytedance/byteps/blob/master/setup.py#L241

I am not entirely sure which environment variables the python setup toolchain would inherent

**Comment by flint-stone** [comment]
Thanks! The workaround works great.
