### ISSUE TITLE
Possible to simulate multi-server behavior on machines with multi GPU?

### ISSUE THREAD

**Issue by flint-stone** [bytedance/byteps#309]
**Describe the bug**
I'm trying to see if I can run the example benchmark script and simulate a multi-machine scenario using the instructions provided [here](https://github.com/bytedance/byteps/blob/4a5b5c9a0d074c3b8c1533f82df5ba1a6ef337f4/docs/step-by-step-tutorial.md#distributed-training-tcp). The single machine scenario works ok on my machine but it seems I wasn't be able to run two workers (and force them to communicate through server/scheduler) using one machine. The only difference I changed is to export NVIDIA_VISIBLE_DEVICES=0,1 for worker 1 and export NVIDIA_VISIBLE_DEVICES=2,3 for worker 2. And specify server ip to be 127.0.0.1. My worker 2 fails with error "Check failed".  I'm providing a list of commands I use to start each process (see screenshot below)

**To Reproduce**

Starting scheduler

<img width="305" alt="Screen Shot 2020-10-23 at 6 39 37 PM" src="https://user-images.githubusercontent.com/1960399/97062123-1c8cd480-155f-11eb-84c6-1fb8c1b4d9cc.png">

Starting server

<img width="291" alt="Screen Shot 2020-10-23 at 6 40 09 PM" src="https://user-images.githubusercontent.com/1960399/97062136-30383b00-155f-11eb-9bc9-e59a2a963f9b.png">

Starting worker 1

<img width="560" alt="Screen Shot 2020-10-23 at 6 40 42 PM" src="https://user-images.githubusercontent.com/1960399/97062160-434b0b00-155f-11eb-9e5c-e17d498777f3.png">

Starting worker 2

<img width="550" alt="Screen Shot 2020-10-23 at 6 41 25 PM" src="https://user-images.githubusercontent.com/1960399/97062179-5bbb2580-155f-11eb-8361-42bb01f5408c.png">

With INFO logging on, here is the output for each of them. 
Scheduler

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1960399/97062286-de43e500-155f-11eb-9245-69c5f3459dca.png">

Server
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1960399/97062254-c4a29d80-155f-11eb-8ee4-02e8ed22cc75.png">

Worker 1

<img width="917" alt="image" src="https://user-images.githubusercontent.com/1960399/97062330-16e3be80-1560-11eb-80d9-76c9579453cc.png">

Worker 2

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1960399/97062351-2cf17f00-1560-11eb-9859-35dc7eb48abe.png">

**Environment (please complete the following information):**
- OS: CentOS Linux release 7.6.1810
- GCC version: gcc (GCC) 5.3.0
- CUDA and NCCL version: CUDA 10.1, NCCL 1.3.4 0
- Framework (TF, PyTorch, MXNet): PyTorch 1.6.0

**Additional context**

It turns out the GPU picked up by the bpslaunch is not what I specified in $NVIDIA_VISIBLE_DEVICES. I printed out the cuda devices set by the second worker and it points to device 0 and 1 (instead of 2,3 as I specified in the environment variable). Although the number of GPU it used is as expected, which is strange. Is it possible to recreate a distributed environment at all on one machine (just for profiling purpose)? Any suggestion on how to force the launcher to pick up the right GPUs to start the jobs? Thanks!

**Comment by ymjiang** [comment]
You can use `CUDA_VISIBLE_DEVICES` ([link](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/)) to control the visible devices for each process. However, the two workers may still have interference on the same machine (e.g., they may share common socket names for local communication), and it'd better to launch them in individual dockers.

**Comment by flint-stone** [comment]
> You can use `CUDA_VISIBLE_DEVICES` ([link](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/)) to control the visible devices for each process. However, the two workers may still have interference on the same machine. One possible problem is that they may share common socket names for local communication, and you can use `BYTEPS_SOCKET_PATH` to specify different paths for them.

Thanks -- I think the shared socket path is the issue.
