### ISSUE TITLE
import bytes.torch error

### ISSUE THREAD

**Issue by wuyujiji** [bytedance/byteps#311]
**Describe the bug**
Excuse me, I build byteps from source, the tensorflow1.15.0 builds and import byteps.tensorflow successfully, but the pytorch builds failed. The error is shown as following:
<img width="1297" alt="截屏2020-10-29 下午4 21 07" src="https://user-images.githubusercontent.com/25579435/97543146-c5757c80-1a02-11eb-89e9-d6af796e2f28.png">

However, I can import torch successfully in this docker envrionment.
<img width="1144" alt="截屏2020-10-29 下午4 17 52" src="https://user-images.githubusercontent.com/25579435/97543288-fce42900-1a02-11eb-9791-7b309bca7906.png">

Could you please help me analyze the problem? thanks a lot!

**Environment (please complete the following information):**
 - OS: centos 7
 - GCC version: 5.3.1
 - CUDA and NCCL version: 10.0 and 7.6
 - Framework (TF, PyTorch): TF 1.15.0 Pytorch 1.4.0

**Comment by ymjiang** [comment]
You may need `export LD_LIBRARY_PATH=/path/to/your/gcc:$LD_LIBRARY_PATH`.

**Comment by wuyujiji** [comment]
which position should I export, before building byteps?

**Comment by wuyujiji** [comment]
I use `source scl_source enable devtoolset-4` to set gcc 5.3.1, the gcc path should be existed in LD_LIBRARY_PATH

**Comment by wuyujiji** [comment]
it solves, the version of gcc is too old, thanks a lot!
