### ISSUE TITLE
[ByteScheduler] Patch file for PyTorch in ByteScheduler

### ISSUE THREAD

**Issue by aoranwu** [bytedance/byteps#314]
I'm confused about this line in the patch file: https://github.com/bytedance/byteps/blob/78ae602da8fdb2ccb3ee666933d6e791102de355/bytescheduler/bytescheduler/pytorch/horovod_pytorch.patch#L23
What does this line do? Should this be  
```
ready = it->ready_event->Ready();
```
instead?

**Comment by pengyanghua** [comment]
@aoranwu Thanks for your feedback and you are right. Would you mind opening a pull request to fix this?

**Comment by pengyanghua** [comment]
The bug is fixed. The code is reorganized based on the original paper version for open source purpose, so it may contain unexpected bugs.
