### ISSUE TITLE
[example] A bug in synthetic_benchmark_tf2.py

### ISSUE THREAD

**Issue by wuyifan18** [bytedance/byteps#315]
**Describe the bug**
There is a bug when I run the synthetic_benchmark_tf2.py.

The first parameter of [tf.losses.categorical_crossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/categorical_crossentropy) should be a tensor of one-hot true targets, but the parameter in this code is just integer. So, we should use [sparse_categorical_crossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/sparse_categorical_crossentropy).

https://github.com/bytedance/byteps/blob/c9abdd531db7e45e8669fd42659c818fec3f4b02/example/tensorflow/synthetic_benchmark_tf2.py#L52-L53
https://github.com/bytedance/byteps/blob/c9abdd531db7e45e8669fd42659c818fec3f4b02/example/tensorflow/synthetic_benchmark_tf2.py#L64 

I have fixed it in #310

**Comment by bobzhuyb** [comment]
Merged.
