### ISSUE TITLE
Error: OS call failed or operation not supported on this OS

### ISSUE THREAD

**Issue by wuyifan18** [bytedance/byteps#321]
**Describe the bug**
I use BytePS/PyTorch training on a single server with 4 P100 GPU, it works fine when setting layers 50 but raise error for layers 152.

**To Reproduce**
1. bpslaunch python benchmark_byteps.py --model resnet152 --num-iters 5
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/27428539/99079695-3ddf5e80-25fb-11eb-905b-14778e6e2139.png)

**Environment (please complete the following information):**
 - OS: ubuntu 16.04
 - GCC version: 4.8.5
 - CUDA and NCCL version: CUDA 10.1
 - Framework (TF, PyTorch, MXNet): PyTorch

**Comment by jasonliu747** [comment]
Facing the same issue, does byteps requires specific library version?
![image](https://user-images.githubusercontent.com/24452340/99642821-e3c11c00-2a86-11eb-9553-3aabdb954ef1.png)

**Comment by bobzhuyb** [comment]
The error looks like that your OS does not allow BytePS to open a big enough share memory. Can you try raising the share memory limit? A few GBs should be sufficient.

**Comment by jasonliu747** [comment]
@bobzhuyb How about this situation?
![image](https://user-images.githubusercontent.com/24452340/99648228-c04d9f80-2a8d-11eb-9ce7-271aa43d6694.png)

**Comment by bobzhuyb** [comment]
@jasonliu747  I see. Your error is different from @wuyifan18 's.

I don't know why such a basic CUDA call would fail 
https://github.com/bytedance/byteps/blob/master/byteps/common/shared_memory.cc#L39

What kind of GPU are you using?

**Comment by jasonliu747** [comment]
@bobzhuyb I'm using 2080Ti. After rollback to #305,, everything works well.
