### ISSUE TITLE
AttributeError: module 'pre_setup' has no attribute 'ucx_path' 

### ISSUE THREAD

**Issue by vycezhong** [bytedance/byteps#329]
I encountered this compile error with the latest commit. 

@pleasantrabbit   Is there something missing in this commit https://github.com/bytedance/byteps/commit/df7095bdac430a09351af75f9798cc497089f85b?

**Comment by pleasantrabbit** [comment]
@vycezhong thanks for the report. I am fixing it.

**Comment by bobzhuyb** [comment]
@pleasantrabbit We should use pull request

**Comment by chenxie95** [comment]
I encountered the same issue. It works well if I pull the image to my local machine

**Comment by bobzhuyb** [comment]
@chenxie95 Can you set `BYTEPS_WITH_UCX=0` when installing it? Or, use an older commit.

**Comment by pleasantrabbit** [comment]
@vycezhong @chenxie95 
It's fixed in the latest master commit. Please give it a try.

**Comment by chenxie95** [comment]
> @vycezhong @chenxie95
> It's fixed in the latest master commit. Please give it a try.

I have just verified the docker build in my local machine. It works for me now. I could build the image successfully.
Many thanks for the quick fix!

**Comment by vycezhong** [comment]
Yes it works. Thanks.
