### ISSUE TITLE
[ByteScheduler] Where is the file or code snippets for removing global barrier for Tensorflow?

### ISSUE THREAD

**Issue by zarzen** [bytedance/byteps#340]
Hi,
Based on the last part of the readme file at [here](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/README.md#limitations) I would expect to find an optimizer rewrite for TensorFlow.

But the `tensorflow` folder here https://github.com/bytedance/byteps/tree/bytescheduler/bytescheduler/bytescheduler/tensorflow does not include an **optimizer/gradientTape** rewrite for overlapping forward and backward. Does it mean the TensorFlow(both v1 & v2) support forward and backward overlapping out-of-box? or we need to customize horovod/byteps optimizer for TensorFlow. 
Thanks!

**Comment by pengyanghua** [comment]
@zarzen Hi, TensorFlow(both v1 & v2) does not support forward and backward overlapping out-of-box. Please check the SGD [here](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L166)

**Comment by zarzen** [comment]
Hi @pengyanghua thanks for pointing me to the SGD part.
Yeah, I can understand the reason you have an out-of-band gradient manager. While it is unclear to me, how could you cross the TensorFlow's optimizer? 
Is this because of the [GraphRewritePass](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L574)? 
Or the other two passes? Could you elaborate a little bit more?

BTW, does the plugin work for horovod+tensorflow?
Thanks!

**Comment by pengyanghua** [comment]
@zarzen It is because of the [PSRewritePass](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L803). The graph on PS is modified using the two ops [SendParameter]( https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L455) and [RecvApplyGradientDescent ](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L403). The plugin does not work for Horovod.

**Comment by zarzen** [comment]
@pengyanghua Thanks for the clarification.
Is it because [here](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L442) at [RecvApplyGradientDescentOp](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L403) one `done()` is called, the computation graph can continue working on its own, while the weights update is managed `OobUpdateManager` .
But how could you lock the forward graph to wait for the gradient update?

**Comment by pengyanghua** [comment]
@zarzen Yes.

The parameter will only be sent after SGD update. See the [poll](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/tensorflow/plugin.cc#L484) implementation.
