### ISSUE TITLE
Whether Pcie becomes a bottleneck after optimization of NVLink topology

### ISSUE THREAD

**Issue by Richie-yan** [bytedance/byteps#345]
BytePS is optimized in the machine under the NVLink topology. 
First, reduce the machine. The user can set reduce_root. 
According to the BytePS paper, the dataflow of the NVLink topology is that GPU6 goes to GPU0 and then to GPU2. But according to the official NV Introduced, for the two GPUs that are not directly connected through NVLink (GPU6 and GPU2 are not directly connected), GPU6 needs to go from Pcie to P3, and finally to GPU2 through P1. Then the Pcie bus between P1 and CPU0 will Become a bottleneck?
<img width="357" alt="截屏2020-12-30 上午10 58 23" src="https://user-images.githubusercontent.com/41471499/103328192-c4a8a780-4a92-11eb-91e0-29d357146c72.png">

**Comment by ymjiang** [comment]
> But according to the official NV Introduced, for the two GPUs that are not directly connected through NVLink (GPU6 and GPU2 are not directly connected), GPU6 needs to go from Pcie to P3, and finally to GPU2 through P1.

We use this figure just to illustrate that we set GPU2 as the reduce root. In the implementation, we use the ``reduce`` API of NCCL that can automatically form a ring on NVLinks (e.g., 4->6->7->5->3->1->0->2), so there won't be traffic on PCIe. It also works well in practice.

**Comment by Richie-yan** [comment]
Thank you for your reply
That is to say, when nccl's automatic ring grouping, it actually connects every two directly connected GPUs together (NCCL will automatically detect which method of the two GPUs is the best), so that it is avoided Pcie is gone
