### ISSUE TITLE
Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid argument

### ISSUE THREAD

**Issue by lizi998** [bytedance/byteps#346]
**Describe** the bug**
Thanks and look forward to your reply.
In my docker，I successfully deployed byteps. But there is a problem with running benchmark_byteps.py with the following command. As follows:

BytePS launching worker
[2020-12-31 08:38:59.299027: F byteps/common/**shared_memory.cc:39**] **Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid argument**
Aborted (core dumped)
Traceback (most recent call last):
  File "/home/byteps_torch/byteps/bin//bpslaunch", line 220, in <module>
    launch_bps()
  File "/home/byteps_torch/byteps/bin//bpslaunch", line 206, in launch_bps
    t[i].join()
  File "/home/byteps_torch/byteps/bin//bpslaunch", line 34, in join
    raise self.exc
  File "/home/byteps_torch/byteps/bin//bpslaunch", line 27, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/byteps_torch/byteps/bin//bpslaunch", line 177, in worker
    stdout=sys.stdout, stderr=sys.stderr, shell=True)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python ./benchmark_byteps.py --model resnet50 --num-iters 5000 --batch-size 2' returned non-zero exit status 134.

**my command**
single machine

export NVIDIA_VISIBLE_DEVICES=0  # gpus list
export DMLC_WORKER_ID=0 # your worker id
export DMLC_NUM_WORKER=1 # one worker
export DMLC_ROLE=worker

export DMLC_NUM_SERVER=1
export DMLC_PS_ROOT_URI=10.0.0.1
export DMLC_PS_ROOT_PORT=1234

bpslaunch python ./benchmark_byteps.py --model resnet50 --num-iters 5000 --batch-size 2

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.7
 - GCC version: 5.4.0
 - CUDA and NCCL version: cuda 10.2.89
 - Framework (TF, PyTorch, MXNet): PyTorch

**Additional context**

**Comment by bobzhuyb** [comment]
What GPU are you using?

**Comment by lizi998** [comment]
> What GPU are you using?

NVIDIA V100

**Comment by bobzhuyb** [comment]
https://github.com/bytedance/byteps/blob/master/byteps/common/shared_memory.cc#L39

This is a simple API call to pin CPU memory for CUDA. I am not sure why it fails. Sometimes it is due to the OS configuration of the limit of locking memory pages. 

Can you try some smaller models in torchvision?

**Comment by lizi998** [comment]
Thank you for your reply. Maybe you are right.  I recreated a docker and specified the shared memory size --shm-size=‘8g’ (The default is 64M).  After installing BYTEPS, benchmark_byteps.py works.
