### ISSUE TITLE
[Question] Why rank=0 always ready in pytorch with bytescheduler

### ISSUE THREAD

**Issue by SimonZYC** [bytedance/byteps#351]
Thanks for your great work on Bytescheduler & BytePS. I have a question on bytescheduler with pytorch.
This [patch](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/pytorch/horovod_pytorch.patch) adds a global state indicating the use of bytescheduler. 
From this, when enabling bytescheduler, rank=0 is always "ready". Why is that? What if we do not apply this patch?

**Comment by pengyanghua** [comment]
@SimonZYC Hi, the readiness of rank 0 is already checked in the python layer. Please check the detailed explanation [here](https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/pytorch/horovod.py#L148).
