### ISSUE TITLE
How byteps find the gpu topology?

### ISSUE THREAD

**Issue by Ruinhuang** [bytedance/byteps#368]
I read the paper,  In chapters 4.2.1 and 4.2.2, there are 2 different topologies, PCIe-only, and  NVLink-based. How does BytePS use the actual topology or which part of the code do I need to set?
@ymjiang

**Comment by ymjiang** [comment]
Sorry for the delay. The way to reproduce our experiments is recorded in this file: https://github.com/byteps/examples/blob/master/osdi20ae.pdf. 

The particular part you are interested in should be here.
![image](https://user-images.githubusercontent.com/13852819/109297640-49cef380-786d-11eb-9166-5da79dd97951.png)

For PCIe topology (with 8 GPUs), you should use `BYTEPS_PCIE_SWITCH_SIZE=4`. 

For NVLink topology, if your topology is the same as in our paper, you can use `BYTEPS_REDUCE_ROOTS=2`.

**Comment by Ruinhuang** [comment]
Thanks for the reply. I have another question. In the paper (https://www.usenix.org/system/files/osdi20-jiang.pdf) chapter 4.2.3. It shows that  BytePS does not use GPU-direct RDMA. But in your experiments file, you can set up DMLC ENABLE RDMA=1 to use RDMA. So is there something I misunderstanding?

**Comment by Ruinhuang** [comment]
Thanks for the reply. I have another question. In the paper (https://www.usenix.org/system/files/osdi20-jiang.pdf) chapter 4.2.3. It shows that  BytePS does not use GPU-direct RDMA. But in your experiments file, you can set up DMLC ENABLE RDMA=1 to use RDMA. So is there something I misunderstanding?

**Comment by ymjiang** [comment]
In our context, GPU-direct RDMA (GDR) is different from the commonly used RDMA. The former transfers data between GPU memory, while the latter transfers data between CPU memory.

**Comment by Ruinhuang** [comment]
ok, got it. Thanks a lot. 
By the way, I think the experiments file's  (https://github.com/byteps/examples/blob/master/osdi20ae.pdf)  image number is wrong with the paper. For example. 
The 4th of A6.1.2 shows that  ` To reproduce Fig. 12(b),`  figure12 in the paper just has one image. so I think it should be figure 13(b). and also I think in this sentence `For the topology like Fig. 7,` Fig7 should be Fig8. 
PLZ have a check

**Comment by Ruinhuang** [comment]
For my understanding is correct. if the topology like Fig. 8 in paper
IF NIC is connected to PCIe 0 -> set BYTEPS_REDUCE_ROOTS = 2 ,3
IF NIC is connected to PCIe 1 -> set BYTEPS_REDUCE_ROOTS = 0, 1
IF NIC is connected to PCIe 2 -> set BYTEPS_REDUCE_ROOTS = 6, 7
IF NIC is connected to PCIe 3 -> set BYTEPS_REDUCE_ROOTS = 4, 5
Is my understanding correct?

**Comment by ymjiang** [comment]
> By the way, I think the experiments file's (https://github.com/byteps/examples/blob/master/osdi20ae.pdf) image number is wrong with the paper. For example.
The 4th of A6.1.2 shows that To reproduce Fig. 12(b), figure12 in the paper just has one image. so I think it should be figure 13(b). and also I think in this sentence For the topology like Fig. 7, Fig7 should be Fig8.
PLZ have a check

You are right.. We added a figure in the paper's camera version, but the AE file was submitted before it. That is why the number is mis-leading. Sorry about that. 

I will fix this. 

> For my understanding is correct. if the topology like Fig. 8 in paper
IF NIC is connected to PCIe 0 -> set BYTEPS_REDUCE_ROOTS = 2 ,3
IF NIC is connected to PCIe 1 -> set BYTEPS_REDUCE_ROOTS = 0, 1
IF NIC is connected to PCIe 2 -> set BYTEPS_REDUCE_ROOTS = 6, 7
IF NIC is connected to PCIe 3 -> set BYTEPS_REDUCE_ROOTS = 4, 5
Is my understanding correct?

Right.

**Comment by Ruinhuang** [comment]
Thanks a lot. 
Before you said that 
> For NVLink topology, if your topology is the same as the one in our paper, you can use BYTEPS_REDUCE_ROOTS=2.

But when i set
IF NIC is connected to PCIe 0 -> set BYTEPS_REDUCE_ROOTS = 2 ,3

Is there any performance difference between these 2 settings?
Is there any difference to set BYTEPS_REDUCE_ROOTS=2 or BYTEPS_REDUCE_ROOTS=2,3?

**Comment by ymjiang** [comment]
The difference is not evident according to our evaluation. See Fig. 14(b).

![image](https://user-images.githubusercontent.com/13852819/109617438-5c00a880-7b71-11eb-812c-680283ba9a41.png)

**Comment by Ruinhuang** [comment]
Thanks a lot:)
