### ISSUE TITLE
import issue in example/pytorch/mnist-distributed.py

### ISSUE THREAD

**Issue by heliumsea** [bytedance/byteps#376]
**Describe the bug**
line 10: 
`from nn.parallel import DistributedDataParallel as DDP`
can't find module for Python 3.8
should be changed into
`from torch.nn.parallel import DistributedDataParallel as DDP`

(I definitely remember from nn.xxx used to work well...)

**To Reproduce**
just run it

**Environment (please complete the following information):**
 - OS: ubuntu 20.04
 - GCC version: 9.3.0
 - CUDA and NCCL version: cuda 10.1
 - Framework (TF, PyTorch, MXNet): PyTorch

**Comment by pleasantrabbit** [comment]
@heliumsea 
Thanks for reporting this issue. It's fixed by https://github.com/bytedance/byteps/pull/379.
