### ISSUE TITLE
Does BytePS support  multiple network interface?

### ISSUE THREAD

**Issue by wuyujiji** [bytedance/byteps#392]
Hello! According to byteps's document, the `DMLC_INTERFACE `seems like support only one network interface such as `DMLC_INTERFACE=eth0 `or`DMLC_INTERFACE=eth1`. Does BytePS support  multiple network interface? such as `DMLC_INTERFACE=eth0, eth1`

**Comment by bobzhuyb** [comment]
Only with the UCX transport

**Comment by wuyujiji** [comment]
@bobzhuyb Could you please explained detailed? I am a newer for network transport. Or If byteps support multiple network interface,  how do I configure and launch it

**Comment by bobzhuyb** [comment]
Build BytePS with `BYTEPS_WITH_UCX=1`. Then enable multi-rail via the UCX environment variables.  http://openucx.github.io/ucx/faq.html  e.g., `UCX_MAX_RNDV_RAILS=2` to use two interfaces. UCX has many options, so it may take you some time to find out what configuration really fits you..

**Comment by wuyujiji** [comment]
Okay, Thanks for your reply!
