### ISSUE TITLE
Distributed training with RDMA errors

### ISSUE THREAD

**Issue by wuyujiji** [bytedance/byteps#397]
Excuse me! When I use [step-by-step-tutorial](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md) to training multi-machines training of RDMA, the error as follows:
![image](https://user-images.githubusercontent.com/25579435/119820183-c97b6580-bf23-11eb-96d2-5b2cf933326b.png)

However，when I run Horovod RDMA training with same machines, it can works normally!
What factors can cause this error to occur?

**Comment by bobzhuyb** [comment]
It's usually because a wrong NIC is chosen. Do you have multiple NICs on a machine? Can you set `DMLC_NODE_HOST` to be the IP of the NIC you want?

**Comment by wuyujiji** [comment]
Yes，I use A100 which has 8 NICs，so I need to set `DMLC_NODE_HOST=scheduler_node_ip`?

**Comment by bobzhuyb** [comment]
Set `'DMLC_NODE_HOST` to be the local IP for the process. I assume you will have 8 processes, one GPU and one NIC per process, right? Think of it as binding processes to the NICs, respectively.

**Comment by bobzhuyb** [comment]
By the way, I am not sure about the multi-NIC support in this open source version. It may not perform well. cc @eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
Should work fine in the 1 process per GPU mode, where each process uses one NIC

**Comment by wuyujiji** [comment]
As @eric-haibin-lin said, I want to use 1 process per GPU mode, where each process uses one NIC. if I select the mlx5_0, how do I configure it?

**Comment by eric-haibin-lin** [comment]
Oh. I misunderstand the question. The current open source version still uses one ps lite worker per node, which won't perform well..

**Comment by wuyujiji** [comment]
If not considered perform firstly，how can I run this demo in A100？In first stage，I only aim to make multi-machine works normally

**Comment by eric-haibin-lin** [comment]
> If not considered perform firstly，how can I run this demo in A100？In first stage，I only aim to make multi-machine training works normally

Sure. You need to select one of the NIC for ps-lite to communicate. You can bind the interface with `DMLC_INTERFACE` (e.g. DMLC_INTERFACE=eth0) and set DMLC_PS_ROOT_URI to the corresponding ip address of that interface (check it via `ip address show`)

**Comment by wuyujiji** [comment]
@bobzhuyb @eric-haibin-lin Have you ever done the benchmark results of the A100 one NIC?，my results  of 16gpus much worse than 8gpus in A100 one NIC environment.

**Comment by wuyujiji** [comment]
Have you planed to implement multiple NICs internally? We want to do multiple NICs development based on bytes, and want to communicate with you！

**Comment by ymjiang** [comment]
Supporting multi NICs is in progress.

**Comment by wuyujiji** [comment]
Could it be convenient to ask when is it planed to open source?

**Comment by wuyujiji** [comment]
Hello, I met another problem. Using 32 GPUs with RDMA to distributed training works well, but when using 64 GPUs with RDMA, it raised a problem as follows:
![image](https://user-images.githubusercontent.com/25579435/122531361-fec23180-d051-11eb-81c5-27ee45f849a6.png)

**Comment by wuyujiji** [comment]
> Excuse me! When I use [step-by-step-tutorial](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md) to training multi-machines training of RDMA, the error as follows:
> ![image](https://user-images.githubusercontent.com/25579435/119820183-c97b6580-bf23-11eb-96d2-5b2cf933326b.png)
> 
> However，when I run Horovod RDMA training with same machines, it can works normally!
> What factors can cause this error to occur?

Hello，as https://github.com/bytedance/byteps/issues/397#issuecomment-850530032 shows，I set the correct （check many times）`DMLC_INTERFACE ` and `DMLC_PS_ROOT_URI`。

**Comment by wuyujiji** [comment]
@eric-haibin-lin Hello, When I set the correct `DMLC_INTERFACE` and `DMLC_PS_ROOT_URI` (check many times), it works well with RDMA on 16 GPUs, but it has errors with RDMA on 32 GPUs as follows:
![image](https://user-images.githubusercontent.com/25579435/122546088-2e2c6a80-d061-11eb-9808-e7cdd57b5d88.png)

The scheduler machine between 16 GPUs and 32 GPUs are same, and I also tried to run 32 GPUs with TCP, it also works well. 

The code of entire experiments process has no change, only change some environment variables, such as "DMLC_NUM_WORKER" , "DMLC_NUM_WORKER" and TCP config sets "DMLC_ENABLE_RDMA=0"

May I ask what caused the 32 GPUs RDMA error？

**Comment by eric-haibin-lin** [comment]
> @eric-haibin-lin Hello, When I set the correct `DMLC_INTERFACE` and `DMLC_PS_ROOT_URI` (check many times), it works well with RDMA on 16 GPUs, but it has errors with RDMA on 32 GPUs as follows:
> 
> ![image](https://user-images.githubusercontent.com/25579435/122546088-2e2c6a80-d061-11eb-9808-e7cdd57b5d88.png)
> 
> 
> 
> The scheduler machine between 16 GPUs and 32 GPUs are same, and I also tried to run 32 GPUs with TCP, it also works well. 
> 
> 
> 
> The code of entire experiments process has no change, only change some environment variables, such as `DMLC_NUM_WORKER` , `DMLC_NUM_SERVER` and TCP config sets `DMLC_ENABLE_RDMA=0`, and the machines are A100.
> 
> 
> 
> May I ask what caused the 32 GPUs RDMA error？
> 
> 

Hi, were you able to run 2 node training with any 2 of these nodes? Just wondering if some node is not configured correctly.

**Comment by wuyujiji** [comment]
@eric-haibin-lin Thanks for your reply！ I tried any 2 of these nodes and could both worker. Besides that, 4nodes of TCP also works normally! Apart from some node is not configured correctly，is there any other reason?

**Comment by wuyujiji** [comment]
> Supporting multi NICs is in progress.

Excuse me! How is the progress of multi NICs support?
