### ISSUE TITLE
install error:fatal error: numa.h: No such file or directory

### ISSUE THREAD

**Issue by windwm** [bytedance/byteps#40]
**Describe the bug**
I meet this problem when I install the byteps.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
byteps/common/global.cc:19:18: fatal error: numa.h: No such file or directory
compilation terminated.
INFO: Unable to build TensorFlow plugin, will skip it.

Traceback (most recent call last):
  File "lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

**To Reproduce**
python setup.py install

**Environment (please complete the following information):**
 - OS:ubuntu16.04
 - GCC version:gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0
 - CUDA and NCCL version:10.0
 - Framework (TF, PyTorch, MXNet):TF

**Comment by bobzhuyb** [comment]
You need this `sudo apt-get install libnuma-dev`

**Comment by bobzhuyb** [comment]
Closing this. Feel free to reopen it.
