### ISSUE TITLE
Is it right to do allreduce immediately for non-zero ranks in bytescheduler?

### ISSUE THREAD

**Issue by sywang0111** [bytedance/byteps#422]
https://github.com/bytedance/byteps/blob/2749848707a414e7dee24a16852575340b6ddd47/bytescheduler/bytescheduler/common/bytecore.py#L192
I see in you code, for rank0, check whether the tensor is ready for allreduce; for other ranks, let them do allreduce immediately. So the rank0 can control other ranks' gradient communication.
But suppose these are some stragglers in non-zero ranks, allreduce occurs as long as the tensor is ready in rank0 although the tensor is not ready in those stragglers .
So can you tell me if there's a problem with my understanding or if it might be a bug here. 
@pengyanghua Thank you.

**Comment by pengyanghua** [comment]
@sywang0111 Hi, other ranks will check their readiness here https://github.com/bytedance/byteps/blob/bytescheduler/bytescheduler/bytescheduler/pytorch/horovod_pytorch.patch#L22

**Comment by sywang0111** [comment]
Understood. Thank you for your reply.
