### ISSUE TITLE
Successfully installed BytePS but cannot import byteps.torch or byteps.tensorflow 

### ISSUE THREAD

**Issue by hamidralmasi** [bytedance/byteps#428]
**Describe the bug**
I have installed BytePS successfully. I have specified the path for NCCL and CUDA and have working tensorflow and pytorch on my system. I'm building BytePS from source and I can see:
"Tensorflow extension is built successfully."
and
"PyTorch extension is built successfully"
in the output. I can also successfully import byteps in python after installation, however, to start my distributed training workloads I need to import byteps.torch and byteps.tensorflow that I get the following errors for:

`import byteps.pytorch`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/halmas3/byteps/byteps/torch/__init__.py", line 24, in <module>
    from byteps.torch.ops import push_pull_async_inplace as byteps_push_pull
  File "/users/halmas3/byteps/byteps/torch/ops.py", line 29, in <module>
    from byteps.torch import c_lib
ImportError: cannot import name 'c_lib' from partially initialized module 'byteps.torch' (most likely due to a circular import) (/users/halmas3/byteps/byteps/torch/__init__.py)

`import byteps.tensorflow`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/halmas3/byteps/byteps/tensorflow/__init__.py", line 27, in <module>
    from byteps.tensorflow.ops import broadcast, _push_pull
  File "/users/halmas3/byteps/byteps/tensorflow/ops.py", line 53, in <module>
    C_LIB = _load_library('c_lib' + get_ext_suffix())
  File "/users/halmas3/byteps/byteps/tensorflow/ops.py", line 49, in _load_library
    library = load_library.load_op_library(filename)
  File "/users/halmas3/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /users/halmas3/byteps/byteps/tensorflow/c_lib.cpython-38-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - GCC version: 9.3.0
 - CUDA and NCCL version: CUDA 11.5, NCCL 2.10.3
 - Framework (TF, PyTorch, MXNet): TF, PyTorch

How can I resolve the issue for each one of these cases?
Thank you so much for your help!

**Comment by hamidralmasi** [comment]
I think I was inside the local byteps folder when importing these and python was not looking at the installed byteps, but rather confused with the local byteps folder inside. Stepping out resolved the issue.

**Comment by ChaosPengs** [comment]
sorry to interrupt but I met the same error. what does 'out the byteps folder' mean? Does it mean if I run the python file out of byteps folder, it will work? I try it but still confront the same error.

**Comment by njqconquer** [comment]
> 不好意思打断一下，我也遇到了同样的错误。“out the bytes folder”是什么意思？是指如果我在bytes文件夹之外运行Python文件，它就能正常工作吗？我试过了，但仍然遇到同样的错误。

你好，我也遇到了同样的问题，请问你的解决了嘛
