### ISSUE TITLE
cuda version must be 9.0 for bytepsimage/worker_pytorch?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#45]

**Comment by bobzhuyb** [comment]
The provided images are for demonstration. You can build yourself's using our docker file https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.pytorch.cu100

This has CUDA 10.0.

**Comment by yangwenhuan** [comment]
> The provided images are for demonstration. You can build yourself's using our docker file https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.pytorch.cu100
> 
> This has CUDA 10.0.

I had seen this Dockerfile before, in fact, I want to know whether it support cuda 8.0?

**Comment by bobzhuyb** [comment]
It should not have any problems. BytePS only uses very basic CUDA functions.

**Comment by yangwenhuan** [comment]
> It should not have any problems. BytePS only uses very basic CUDA functions.

nice, thx!

**Comment by ymjiang** [comment]
Closing this issue. Feel free to reopen if anything comes up.
