### ISSUE TITLE
Did this support FP16？

### ISSUE THREAD

**Issue by MarvinLong** [bytedance/byteps#47]
The mixed precision can speed up training, I can not find the fp16 information in you project. So did you support fp16?

**Comment by bobzhuyb** [comment]
Yes, and in fact we are working on a PR that improves the performance. https://github.com/bytedance/byteps/pull/46

This PR is for the worker side. The server side leverages MXNet fp16 implementation.

**Comment by MarvinLong** [comment]
@bobzhuyb 
Thank you for your great jobs!
