### ISSUE TITLE
Parameter sharding ?

### ISSUE THREAD

**Issue by chunyang-wen** [bytedance/byteps#50]
Hi,

I am just curious. In your document, you specify that:

+ PS: do gradient reduction
+ Worker: apply gradient update

So does it mean that each worker should hold all the parameters ?

**Comment by ymjiang** [comment]
Yes, we use data parallelism.

**Comment by chunyang-wen** [comment]
So when we increase the size of parameters which may exceed the limit of a single machine, byteps currently cannot handle this kind of situation.

**Comment by ymjiang** [comment]
You are right. Though most popular DNNs (Resnet, VGG, BERT, etc) we know so far can fit into a single machine (or more specifically, single GPU), there could be some exceptionally large models as you said. For now BytePS focuses on data-parallelism.

**Comment by ymjiang** [comment]
You are right. Though most popular DNNs (Resnet, VGG, BERT, etc) we know so far can fit into a single machine (or more specifically, single GPU), there could be some exceptionally large models as you said. For now BytePS focuses on data-parallelism.

**Comment by yangwenhuan** [comment]
@ymjiang, the reason why each worker should hold all the parameters is that some parameters update depending on some other parameters?

**Comment by ymjiang** [comment]
@yangwenhuan Of course, the dependency is the nature of DNN training.

**Comment by bobzhuyb** [comment]
Closing this. Feel free to reopen it.
