### ISSUE TITLE
src/./zmq_van.h:304: Check failed: 0 failed to receive message. errno: 88 Socket operation on non-socket

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#51]
@ymjiang, I met a similar problem with closed issue 49 in pytorch benchmark. I used 8 GPUs in total with 2 wokers. How can I fix it?

Iter #992: 43.5 img/sec per GPU
Iter #993: 46.1 img/sec per GPU
Iter #994: 41.1 img/sec per GPU
Iter #995: 48.6 img/sec per GPU
Iter #996: 50.1 img/sec per GPU
Iter #997: 49.4 img/sec per GPU
Iter #998: 42.5 img/sec per GPU
Traceback (most recent call last):
File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in 
raise Exception
Exception
Traceback (most recent call last):
File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in 
raise Exception
Exception
Traceback (most recent call last):
File "/usr/local/byteps/example/pytorch/benchmark_byteps.py", line 132, in 
raise Exception
Exception
Iter #999: 41.3 img/sec per GPU
[16:25:36] 3rdparty/ps-lite/include/dmlc/logging.h:276: [16:25:36] src/./zmq_van.h:304: Check failed: 0 failed to receive message. errno: 88 Socket operation on non-socket

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so(+0x2e1e8) [0x7f0cc47b81e8]
[bt] (1) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so(+0x2f109) [0x7f0cc47b9109]
[bt] (2) /usr/local/lib/python2.7/dist-packages/byteps-0.1.0-py2.7-linux-x86_64.egg/byteps/torch/c_lib.so(+0x8c4e8) [0x7f0cc48164e8]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f0cd56edc80]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f0cda1f06ba]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f0cd9f2641d]

**Comment by ymjiang** [comment]
I already answered this question here: https://github.com/bytedance/byteps/issues/49#issuecomment-509906700

**Comment by ymjiang** [comment]
@yangwenhuan For clarity, please avoid proposing the same issue at two different sites. If you have further questions please propose them here. If not, please close this issue.
