### ISSUE TITLE
RDMA like RoCE must support cuda10?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#62]

**Comment by ymjiang** [comment]
RDMA does not necessarily needs cuda10. For now we only provide docker files with cuda10 that support RDMA. But you can try to build your own cuda9+RDMA image.

**Comment by yangwenhuan** [comment]
@ymjiang 
![image](https://user-images.githubusercontent.com/5866456/61298028-1a8e7e80-a810-11e9-8e4e-d082ab30bad0.png)

**Comment by ymjiang** [comment]
The images we provide need cuda10. But like I said, you can build your own images with cuda9, and make sure to install RDMA drivers properly.

**Comment by yangwenhuan** [comment]
@ymjiang , I used RoCE, but got 'unreachable' error, did it matter with network bonding? 

![image](https://user-images.githubusercontent.com/5866456/61342663-91159580-a87d-11e9-98e0-de3b8ec8c3af.png)

**Comment by ymjiang** [comment]
Did you set `DMLC_PS_ROOT_URI` and `DMLC_INTERFACE` correctly according to your RDMA device?

Can you run through [this benchmark] with RDMA (https://github.com/bytedance/byteps/blob/master/docs/troubleshooting.md#network-connectivity)?

**Comment by yangwenhuan** [comment]
@ymjiang , I am not sure about DMLC_INTERFACE, how to check it?

![image](https://user-images.githubusercontent.com/5866456/61370527-2d16bf80-a8c5-11e9-8f15-cc2269db96ce.png)

![image](https://user-images.githubusercontent.com/5866456/61370567-40c22600-a8c5-11e9-897b-ca6241695d83.png)

**Comment by ymjiang** [comment]
Looks like you are using docker. When you launch the docker container, do you add the `--device` arguments as shown in the [tutorial](https://github.com/bytedance/byteps/blob/master/docs/step-by-step-tutorial.md#distributed-training-with-rdma)?

**Comment by yangwenhuan** [comment]
> @ymjiang , I am not sure about DMLC_INTERFACE, how to check it?
> 
> ![image](https://user-images.githubusercontent.com/5866456/61370527-2d16bf80-a8c5-11e9-8f15-cc2269db96ce.png)
> 
> ![image](https://user-images.githubusercontent.com/5866456/61370567-40c22600-a8c5-11e9-897b-ca6241695d83.png)

@ymjiang , this is the screenshot of my host machine, not in docker.

**Comment by yangwenhuan** [comment]
> @ymjiang , I used RoCE, but got 'unreachable' error, did it matter with network bonding?
> 
> ![image](https://user-images.githubusercontent.com/5866456/61342663-91159580-a87d-11e9-98e0-de3b8ec8c3af.png)

this screenshot is in docker, and I did specify --device option:

docker run -it --net=host --device /dev/infiniband/rdma_cm --device /dev/infiniband/issm0 --device /dev/infiniband/ucm0 --device /dev/infiniband/umad0 --device /dev/infiniband/uverbs0 --cap-add IPC_LOCK bytepsimage/byteps_server_rdma bash

**Comment by bobzhuyb** [comment]
This may be due to bonding. I am not sure. Can you try ib_write_bw with rdma_cm enabled? It should be `ib_write_bw -z`, or `ib_write_bw --com_rdma_cm`

**Comment by yangwenhuan** [comment]
> This may be due to bonding. I am not sure. Can you try ib_write_bw with rdma_cm enabled? It should be `ib_write_bw -z`, or `ib_write_bw --com_rdma_cm`
> 
> Can you also check the configuration details of bonding here https://community.mellanox.com/s/article/howto-create-linux-bond--lag--interface-over-infiniband-network
> 
> Quote:
> 
> ```
> Since rdma_cm does not support MAC enslavement, fail_over_mac=1 (or active) should be added to the bond interface configuration in case of Ethernet interface.
> ```

[root@TENCENT64 ~]# ib_send_bw -d mlx4_0 -x 0 -F --report_gbits 10.0.1.26
---------------------------------------------------------------------------------------
                    Send BW Test
 Dual-port       : OFF		Device         : mlx4_0
 Number of qps   : 1		Transport type : IB
 Connection type : RC		Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 1024[B]
 Link type       : Ethernet
 Gid index       : 0
 Max inline data : 0[B]
 rdma_cm QPs	 : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x0278 PSN 0xbf30b8
 GID: 254:128:00:00:00:00:00:00:238:13:154:255:254:06:186:209
 remote address: LID 0000 QPN 0x02ac PSN 0xb40c4e
 GID: 254:128:00:00:00:00:00:00:238:13:154:255:254:06:187:145
---------------------------------------------------------------------------------------
 #bytes     #iterations    BW peak[Gb/sec]    BW average[Gb/sec]   MsgRate[Mpps]
 65536      1000             8.92               8.90   		   0.016982
---------------------------------------------------------------------------------------

I had tried before, it seemed ok.

**Comment by yangwenhuan** [comment]
> This may be due to bonding. I am not sure. Can you try ib_write_bw with rdma_cm enabled? It should be `ib_write_bw -z`, or `ib_write_bw --com_rdma_cm`
> 
> Can you also check the configuration details of bonding here https://community.mellanox.com/s/article/howto-create-linux-bond--lag--interface-over-infiniband-network
> 
> Quote:
> 
> ```
> Since rdma_cm does not support MAC enslavement, fail_over_mac=1 (or active) should be added to the bond interface configuration in case of Ethernet interface.
> ```

![image](https://user-images.githubusercontent.com/5866456/61446154-4f6e1300-a981-11e9-9705-ba0016a271de.png)

I had tried before, it seems ok.

**Comment by bobzhuyb** [comment]
@yangwenhuan As I said, please use the rdma_cm option when running.ib_send_bw
