### ISSUE TITLE
RDMA docker image must build on machines that support rdma?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#64]

**Comment by ymjiang** [comment]
That is not a necessity. For example, you should be able to build [this](https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.mxnet.cu100.rdma) on a machine that does not support RDMA.

**Comment by ymjiang** [comment]
That is not a necessity. For example, you should be able to build [this](https://github.com/bytedance/byteps/blob/master/docker/Dockerfile.worker.mxnet.cu100.rdma) on a machine that does not support RDMA.
