### ISSUE TITLE
Does byteps support RoCE v1?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#65]

**Comment by changlan** [comment]
BytePS (or more precisely the RDMA implementation of PSLite) uses libibverbs/librdmacm. It supports any RDMA interface (including ROCE v1) that provides a verbs device to the userspace library libibverbs/librdmacm.

**Comment by yangwenhuan** [comment]
@changlan , how does byteps determine to use RoCE v1 or RoCE v2？

**Comment by bobzhuyb** [comment]
@yangwenhuan It's determined by the NIC driver, not byteps
