### ISSUE TITLE
Does byteps support online distributed inference?

### ISSUE THREAD

**Issue by longside** [bytedance/byteps#75]
I'm always frustrated when I want to do my online inference using a large model.
Does byteps support online distributed inference?

**Comment by ymjiang** [comment]
No. BytePS only focuses on training for now. 

Just curious, how big is your inference model?

**Comment by longside** [comment]
> No. BytePS only focuses on training for now.
> 
> Just curious, how big is your inference model?
i gather a large-scale LR model, size up to TB.
It's quite hard to serve this model on single machine.
Any solutions or ideas to this problem in the industry?

**Comment by ymjiang** [comment]
Sounds like a sparse scenario. You may probably take a look at systems for recommendation.

**Comment by ymjiang** [comment]
Closing this since it is out of our scope.
