### ISSUE TITLE
AttributeError: module 'byteps.tensorflow' has no attribute 'allreduce'

### ISSUE THREAD

**Issue by ppwwyyxx** [bytedance/byteps#8]
**Describe the bug**
It was claimed in the README that:
> If your tasks only rely on Horovod's allreduce and broadcast, you should be able to switch to BytePS in 1 minute. Simply replace import horovod.tensorflow as hvd by import byteps.tensorflow as bps, and then replace all hvd in your code by bps.

However, `bps.allreduce` does not exist.

**To Reproduce**
1. `import byteps.tensorflow as bps; bps.allreduce`

Error:
```
AttributeError: module 'byteps.tensorflow' has no attribute 'allreduce'
```

**Comment by bobzhuyb** [comment]
You are right. allreduce has been renamed to push_pull in BytePS. We will update the documentation. Please also let us know if bps.push_pull works for you.

**Comment by bobzhuyb** [comment]
Added description in README.md. Closing this. Feel free to reopen if needed.

**Comment by boscotsang** [comment]
I used hps.allreduce and an error was raised
`AttributeError: module 'byteps.torch' has no attribute 'allreduce'`
However, I replace hvd.allreduce with hps.push_pull, there was alos an error
`AttributeError: module 'byteps.torch' has no attribute 'push_pull'`
