### ISSUE TITLE
Threads never end

### ISSUE THREAD

**Issue by arnaudfroidmont** [bytedance/byteps#85]
I'm running the BytePS for tensorflow in an Nvidia-docker on a machine with 2 P100. Everything runs fine except that the thread never end. I see the log of the results but the threads are stuck. I can see them on the GPUs but at 0% utilisation. 

Any idea of what's going on?

**Comment by ymjiang** [comment]
Thanks for the report, we will check this. For now you may need to kill the process manually.

**Comment by arnaudfroidmont** [comment]
Thanks for the answer Yimin.

**Comment by GitHub-HongweiZhang** [comment]
Hi, is this problem already fixed?

**Comment by bobzhuyb** [comment]
I believe that this has been fixed in https://github.com/bytedance/byteps/pull/136 . Closing this issue for now. Feel free to open if the problem persists.
