### ISSUE TITLE
Does BytePS use async SGD?

### ISSUE THREAD

**Issue by yangwenhuan** [bytedance/byteps#87]
![image](https://user-images.githubusercontent.com/5866456/63515991-aafe6400-c51e-11e9-942b-2825f4b6ade8.png)
I think BytePS use sync SGD, it should not start training next batch until all workers get the updated weights.

**Comment by bobzhuyb** [comment]
This synchronization cost refers to the additional synchronization before AllReduce when you use Horovod. In Horovod, it's called NEGOTIATE_ALLREDUCE in its timeline https://github.com/horovod/horovod/blob/master/docs/timeline.rst

PS architecture does not have this overhead.

**Comment by yangwenhuan** [comment]
another question: weight broadcast communication time does not grow linearly with workers number?

in my opinion, ps architecture is like the naive all reduce as following except for GPU0 replaced by ps.

![image](https://user-images.githubusercontent.com/5866456/63517272-42fd4d00-c521-11e9-9106-f42ee8be3259.png)

**Comment by bobzhuyb** [comment]
If you read the code, you'll find that we are using ReduceScatter + AllGather, instead of Reduce+Broadcast

**Comment by yangwenhuan** [comment]
> If you read the code, you'll find that we are using ReduceScatter + AllGather, instead of Reduce+Broadcast

ReduceScatter + AllGather? it's the implementation of ring all reduce, thx, I will check the code in detail.

**Comment by bobzhuyb** [comment]
Within a worker, we use ReduceScatter + AllGather;
Across different workers, it's more like Reduce + Broadcast. However, if you keep the number of PS the same as workers, the communication time will stay constant in theory.

**Comment by yangwenhuan** [comment]
> Within a worker, we use ReduceScatter + AllGather;
> Across different workers, it's more like Reduce + Broadcast. However, if you keep the number of PS the same as workers, the communication time will stay constant in theory.

got it! I think so too.

besides, could you show some concrete utilization rate of these techniques as following? I think these are strongly depend on specified models.

![image](https://user-images.githubusercontent.com/5866456/63520469-60351a00-c527-11e9-992a-13e0dd5d0dda.png)

**Comment by bobzhuyb** [comment]
There is no communication between different servers.

These optimizations in general do not depend on model details, though some models may benefit more than others.

**Comment by yangwenhuan** [comment]
> There is no communication between different servers.

so, each server node should hold all the weights, and receive gradients from all workers for updating weights, and then push updated weights back to all workers?

![image](https://user-images.githubusercontent.com/5866456/63563959-b2ad1f80-c595-11e9-8218-ba3258b40647.png)

![image](https://user-images.githubusercontent.com/5866456/63563967-c2c4ff00-c595-11e9-8a09-198c23f3e348.png)

**Comment by bobzhuyb** [comment]
“each server node should hold all the weights” -- no, the weights are sharded onto different server nodes.

**Comment by yangwenhuan** [comment]
> “each server node should hold all the weights” -- no, the weights are sharded onto different server nodes.

I think "weights" should be "gradients". That is, workers do weights updating, while servers do gradients global reducing and do not hold weights. This opinion could match source code that push_pull_aync will pipeline well. Am I wrong?

**Comment by bobzhuyb** [comment]
> > “each server node should hold all the weights” -- no, the weights are sharded onto different server nodes.
> 
> I think "weights" should be "gradients". That is, workers do weights updating, while servers do gradients global reducing and do not hold weights. This opinion could match source code that push_pull_aync will pipeline well. Am I wrong?

Right, servers only do gradient reducing and do not store weights.
