### ISSUE TITLE
Does it need to copy the whole train/test data to all worker machines in advance?

### ISSUE THREAD

**Issue by GitHub-HongweiZhang** [bytedance/byteps#89]
as title!

**Comment by bobzhuyb** [comment]
Data IO is irrelevant to BytePS. You can choose to read them locally, or read them from a remote storage.

**Comment by GitHub-HongweiZhang** [comment]
@bobzhuyb 

Thank you for your reply.
I know Data IO is irrelevant to BytePS. 

From the code, when reading them locally, it seems all workers should keep a copy, is it right? 
https://github.com/bytedance/byteps/blob/master/example/tensorflow/tensorflow_mnist.py#L100

**Comment by bobzhuyb** [comment]
@GitHub-HongweiZhang That particular example may require you to do so. You can modify it if you want. It's just an example.
