### ISSUE TITLE
BytePS requires root permission

### ISSUE THREAD

**Issue by ppwwyyxx** [bytedance/byteps#9]
**Describe the bug**
BytePS needs to create socket hard-coded at this path:
https://github.com/bytedance/byteps/blob/b9811f75382b20d45dae57c277bd2d259aedea13/byteps/common/communicator.h#L34-L35

As a result, BytePS cannot be used without root permission. Running BytePS without root permission gives:
```
[2019-06-27 11:01:05.326916: F byteps/common/communicator.cc:135] Check failed: (ret) >= (0) /usr/local/socket_send_0 bind failed: Permission denied
```

**Comment by bobzhuyb** [comment]
We will make these paths configurable.

**Comment by ymjiang** [comment]
Thank you for the report. 

@bobzhuyb Let me update the path configuration code.

**Comment by ymjiang** [comment]
@ppwwyyxx Commit `5dabf0c` should fix this. The default path is changed to /tmp. You can also configure the path by setting `BYTEPS_SOCKET_PATH` to like /your/path.
Let me know if it works for you.

**Comment by ppwwyyxx** [comment]
Thanks for the quick response!
