### ISSUE TITLE
when was the tensorflow version of bytescheduler released

### ISSUE THREAD

**Issue by zhaiyuyong** [bytedance/byteps#90]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ymjiang** [comment]
@yhpeng-git Hi, mind share some updates on bytescheduler-tensorflow?

**Comment by yhpeng-git** [comment]
@zhaiyuyong We are preparing the open source version and it will be released soon.

**Comment by zhaiyuyong** [comment]
@yhpeng-git is there any specific time?

**Comment by yhpeng-git** [comment]
@zhaiyuyong  I think we can make it within this week.

**Comment by yhpeng-git** [comment]
@zhaiyuyong Please check https://github.com/bytedance/byteps/tree/bytescheduler/bytescheduler/bytescheduler/tensorflow

**Comment by zhaiyuyong** [comment]
@yhpeng-git thx
