### ISSUE TITLE
bytescheduler with TF， NotFoundError in libplugin.so

### ISSUE THREAD

**Issue by snowpeakz** [bytedance/byteps#98]
hi,
I have a problem in applying bytescheduler in TF.
TensorFlow was compiled with the patch, libplugin.so was generated by running the Makefile with the same version of gcc. 
tf.load_library('./libplugin.so') was added to my python script.

But it throw a NotFoundError when loading the libplugin.so.
Here is the traceback
```
Traceback (most recent call last):
  File "test/entry.py", line 11, in <module>
    tf.load_library('/lib/libplugin.so')
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 158, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /lib/libplugin.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```
I have tried complie plugin.cc with -D_GLIBCXX_USE_CXX11_ABI=0, it still throw a NotFoundError .
Thanks

**Comment by ligonzheng** [comment]
This maybe caused by your makefile of libplugin.so and you may need  to recompile it with RTTI option.
Please refer to : https://blog.csdn.net/ai2000ai/article/details/47152133

**Comment by ymjiang** [comment]
@yhpeng-git Any idea on this?

And thanks for the notes @ligonzheng .

**Comment by snowpeakz** [comment]
> This maybe caused by your makefile of libplugin.so and you may need to recompile it with RTTI option.
> Please refer to : https://blog.csdn.net/ai2000ai/article/details/47152133

@ligonzheng libplugin compile failed with -fno-rtti option, it says "error: cannot use typeid with -fno-rtti"

**Comment by yhpeng-git** [comment]
@snowpeakz can you provide more debugging information, including versions of TF, GCC and the makefile.

**Comment by snowpeakz** [comment]
> @snowpeakz can you provide more debugging information, including versions of TF, GCC and the makefile.

@yhpeng-git Here it is
TF version: r1.12.0 
gcc version 5.4.0
OS: Ubuntu16.04
no CUDA or NCCL
Makefile:
```
TF_COMPILE_FLAGS := $(shell python -c "import tensorflow as tf;  print(' '.join(tf.sysconfig.get_compile_flags()))")

TF_LINK_FLAGS:= $(shell python -c "import tensorflow as tf;  print(' '.join(tf.sysconfig.get_link_flags()))")

all:
        c++ -O3 -rdynamic -std=c++11 $(TF_COMPILE_FLAGS) -fPIC -Wall -c plugin.cc -o plugin.o
        c++ -shared -fPIC -Wl,-soname,libplugin.so.1 $(TF_LINK_FLAGS) -o libplugin.so plugin.o
        @rm plugin.o

clean:
        @rm libplugin.so

.PHONY: all clean
```

**Comment by yhpeng-git** [comment]
@snowpeakz Can you try TF 1.13? We did not test the plugin with TF 1.12.

**Comment by snowpeakz** [comment]
> @snowpeakz Can you try TF 1.13? We did not test the plugin with TF 1.12.

@yhpeng-git yes, I will try it.

**Comment by snowpeakz** [comment]
> @snowpeakz Can you try TF 1.13? We did not test the plugin with TF 1.12.

@yhpeng-git   TF 1.13 throw a same error. So I put plugin.cc into tensorflow project and build them together. 
I have a another question about usage. How can I start bytescheduler Core, since there is no changes to training script, except tf.load_library('./libplugin.so') .
It seems that the bytescheduler is independent with byteps. I'm now using original tensorflow, will it work?
thanks!

**Comment by yhpeng-git** [comment]
@snowpeakz Unlike other frameworks (e.g., PyTorch), for tensorflow the scheduling logic is in plugin.cc instead of the Core, although the plugin may be able to expose an interface to Core for scheduling.

For usage, they are independent right now and please use native tensorflow PS when enabling bytescheduler.

**Comment by wangshuaizs** [comment]
> @snowpeakz Unlike other frameworks (e.g., PyTorch), for tensorflow the scheduling logic is in plugin.cc instead of the Core, although the plugin may be able to expose an interface to Core for scheduling.
> 
> For usage, they are independent right now and please use native tensorflow PS when enabling bytescheduler.

Hi, @pengyanghua , if I only need tensorflow, do I just need to recompile tensorflow with plugin.cc? Do I still need to execute `BYTESCHEDULER_WITHOUT_MXNET=1 BYTESCHEDULER_WITHOUT_PYTORCH=1 python2 setup.py install && python3 setup.py install`? 

And for usage, I only need to add `tf.load_library('./libplugin.so')` at the beginning of `.py` file to acheive the performance shown in the SOSP'19 paper?

Thanks

**Comment by pengyanghua** [comment]
@wangshuaizs  Just recompile with plugin.cc and the patch. No need to run python install command. For usage, you also need to partition parameters manually. Check https://github.com/bytedance/byteps/tree/bytescheduler/bytescheduler#tensorflow for details.

**Comment by wangshuaizs** [comment]
> > @snowpeakz Can you try TF 1.13? We did not test the plugin with TF 1.12.
> 
> @yhpeng-git TF 1.13 throw a same error. So I put plugin.cc into tensorflow project and build them together.
> I have a another question about usage. How can I start bytescheduler Core, since there is no changes to training script, except tf.load_library('./libplugin.so') .
> It seems that the bytescheduler is independent with byteps. I'm now using original tensorflow, will it work?
> thanks!

Hi, @snowpeakz , I met the same problem `undefined symbol: _ZTIN10tensorflow8OpKernelE`. And I tried `D_GLIBCXX_USE_CXX11_ABI=0` as you did, but it didn't work. Where should I put `plugin.cc` in TensorFlow, and how to build it with TF?

And @pengyanghua , any solution?

**Comment by Rivendile** [comment]
> > @snowpeakz Can you try TF 1.13? We did not test the plugin with TF 1.12.
> 
> @yhpeng-git TF 1.13 throw a same error. So I put plugin.cc into tensorflow project and build them together.
> I have a another question about usage. How can I start bytescheduler Core, since there is no changes to training script, except tf.load_library('./libplugin.so') .
> It seems that the bytescheduler is independent with byteps. I'm now using original tensorflow, will it work?
> thanks!

I run into this error too, and could you please tell me how to put plugin.cc into TensorFlow project and build them together? Thanks a lot!
